const ALL_CARDS = [

        // === FLAGS (no country name shown, no "from X" hints) ===
        { name: "United States", emoji: "🇺🇸", year: 1776, type: "flag" },
        { name: "France", emoji: "🇫🇷", year: 1794, type: "flag" },
        { name: "Brazil", emoji: "🇧🇷", year: 1822, type: "flag" },
        { name: "Italy", emoji: "🇮🇹", year: 1861, type: "flag" },
        { name: "Germany", emoji: "🇩🇪", year: 1871, type: "flag" },
        { name: "Australia", emoji: "🇦🇺", year: 1901, type: "flag" },
        { name: "Israel", emoji: "🇮🇱", year: 1948, type: "flag" },
        { name: "India", emoji: "🇮🇳", year: 1947, type: "flag" },
        { name: "South Sudan", emoji: "🇸🇸", year: 2011, type: "flag" },
        { name: "Pakistan", emoji: "🇵🇰", year: 1947, type: "flag" },
        { name: "South Africa", emoji: "🇿🇦", year: 1994, type: "flag" },
        { name: "Japan", emoji: "🇯🇵", year: 1870, type: "flag" },
        { name: "Mexico", emoji: "🇲🇽", year: 1821, type: "flag" },
        { name: "Greece", emoji: "🇬🇷", year: 1829, type: "flag" },
        { name: "Canada", emoji: "🇨🇦", year: 1965, type: "flag" },
        { name: "China", emoji: "🇨🇳", year: 1949, type: "flag" },
        { name: "Russia", emoji: "🇷🇺", year: 1991, type: "flag" },
        { name: "Turkey", emoji: "🇹🇷", year: 1923, type: "flag" },
        { name: "Argentina", emoji: "🇦🇷", year: 1816, type: "flag" },
        { name: "Nigeria", emoji: "🇳🇬", year: 1960, type: "flag" },
        { name: "Indonesia", emoji: "🇮🇩", year: 1945, type: "flag" },
        { name: "South Korea", emoji: "🇰🇷", year: 1948, type: "flag" },
        { name: "Ireland", emoji: "🇮🇪", year: 1922, type: "flag" },
        { name: "Egypt", emoji: "🇪🇬", year: 1984, type: "flag" },
        { name: "Norway", emoji: "🇳🇴", year: 1905, type: "flag" },
        { name: "Poland", emoji: "🇵🇱", year: 1918, type: "flag" },
        { name: "Colombia", emoji: "🇨🇴", year: 1810, type: "flag" },
        { name: "Thailand", emoji: "🇹🇭", year: 1917, type: "flag" },
        { name: "Vietnam", emoji: "🇻🇳", year: 1945, type: "flag" },
        { name: "Kenya", emoji: "🇰🇪", year: 1963, type: "flag" },
        { name: "Ukraine", emoji: "🇺🇦", year: 1991, type: "flag" },
        { name: "Chile", emoji: "🇨🇱", year: 1818, type: "flag" },
        { name: "Saudi Arabia", emoji: "🇸🇦", year: 1932, type: "flag" },
        { name: "Jamaica", emoji: "🇯🇲", year: 1962, type: "flag" },
        { name: "Nepal", emoji: "🇳🇵", year: 1962, type: "flag" },
        { name: "Cuba", emoji: "🇨🇺", year: 1902, type: "flag" },
        { name: "Ethiopia", emoji: "🇪🇹", year: 1897, type: "flag" },
        { name: "UAE", emoji: "🇦🇪", year: 1971, type: "flag" },
        { name: "Switzerland", emoji: "🇨🇭", year: 1848, type: "flag" },
        { name: "Denmark", emoji: "🇩🇰", year: 1219, type: "flag" },
        { name: "United Kingdom", emoji: "🇬🇧", year: 1801, type: "flag" },
        { name: "Spain", emoji: "🇪🇸", year: 1981, type: "flag" },
        { name: "Portugal", emoji: "🇵🇹", year: 1910, type: "flag" },
        { name: "Sweden", emoji: "🇸🇪", year: 1906, type: "flag" },
        { name: "Finland", emoji: "🇫🇮", year: 1917, type: "flag" },
        { name: "Belgium", emoji: "🇧🇪", year: 1830, type: "flag" },
        { name: "Netherlands", emoji: "🇳🇱", year: 1815, type: "flag" },
        { name: "Austria", emoji: "🇦🇹", year: 1230, type: "flag" },
        { name: "Czech Republic", emoji: "🇨🇿", year: 1993, type: "flag" },
        { name: "Romania", emoji: "🇷🇴", year: 1848, type: "flag" },
        { name: "Hungary", emoji: "🇭🇺", year: 1918, type: "flag" },
        { name: "Croatia", emoji: "🇭🇷", year: 1991, type: "flag" },
        { name: "Serbia", emoji: "🇷🇸", year: 2006, type: "flag" },
        { name: "Iceland", emoji: "🇮🇸", year: 1944, type: "flag" },
        { name: "New Zealand", emoji: "🇳🇿", year: 1907, type: "flag" },
        { name: "Philippines", emoji: "🇵🇭", year: 1898, type: "flag" },
        { name: "Malaysia", emoji: "🇲🇾", year: 1963, type: "flag" },
        { name: "Singapore", emoji: "🇸🇬", year: 1965, type: "flag" },
        { name: "Bangladesh", emoji: "🇧🇩", year: 1971, type: "flag" },
        { name: "Peru", emoji: "🇵🇪", year: 1821, type: "flag" },
        { name: "Venezuela", emoji: "🇻🇪", year: 1811, type: "flag" },
        { name: "Ecuador", emoji: "🇪🇨", year: 1830, type: "flag" },
        { name: "Morocco", emoji: "🇲🇦", year: 1956, type: "flag" },
        { name: "Tunisia", emoji: "🇹🇳", year: 1956, type: "flag" },
        { name: "Algeria", emoji: "🇩🇿", year: 1962, type: "flag" },
        { name: "Ghana", emoji: "🇬🇭", year: 1957, type: "flag" },
        { name: "Tanzania", emoji: "🇹🇿", year: 1964, type: "flag" },
        { name: "Libya", emoji: "🇱🇾", year: 2011, type: "flag" },
        { name: "Iraq", emoji: "🇮🇶", year: 1932, type: "flag" },
        { name: "Iran", emoji: "🇮🇷", year: 1980, type: "flag" },
        { name: "Jordan", emoji: "🇯🇴", year: 1946, type: "flag" },
        { name: "Lebanon", emoji: "🇱🇧", year: 1943, type: "flag" },
        { name: "Qatar", emoji: "🇶🇦", year: 1971, type: "flag" },
        { name: "Bahrain", emoji: "🇧🇭", year: 1971, type: "flag" },
        { name: "Kuwait", emoji: "🇰🇼", year: 1961, type: "flag" },
        { name: "Oman", emoji: "🇴🇲", year: 1970, type: "flag" },
        { name: "Panama", emoji: "🇵🇦", year: 1903, type: "flag" },
        { name: "Costa Rica", emoji: "🇨🇷", year: 1821, type: "flag" },
        { name: "Dominican Republic", emoji: "🇩🇴", year: 1844, type: "flag" },
        { name: "Haiti", emoji: "🇭🇹", year: 1804, type: "flag" },
        { name: "Bolivia", emoji: "🇧🇴", year: 1825, type: "flag" },
        { name: "Paraguay", emoji: "🇵🇾", year: 1811, type: "flag" },
        { name: "Uruguay", emoji: "🇺🇾", year: 1825, type: "flag" },
        { name: "Sri Lanka", emoji: "🇱🇰", year: 1948, type: "flag" },
        { name: "Myanmar", emoji: "🇲🇲", year: 2010, type: "flag" },
        { name: "Cambodia", emoji: "🇰🇭", year: 1953, type: "flag" },
        { name: "Laos", emoji: "🇱🇦", year: 1975, type: "flag" },
        { name: "Mongolia", emoji: "🇲🇳", year: 1911, type: "flag" },
        { name: "North Korea", emoji: "🇰🇵", year: 1948, type: "flag" },
        { name: "Afghanistan", emoji: "🇦🇫", year: 1919, type: "flag" },
        { name: "Congo (DRC)", emoji: "🇨🇩", year: 1960, type: "flag" },
        { name: "Mozambique", emoji: "🇲🇿", year: 1975, type: "flag" },
        { name: "Zimbabwe", emoji: "🇿🇼", year: 1980, type: "flag" },
        { name: "Namibia", emoji: "🇳🇦", year: 1990, type: "flag" },
        { name: "Eritrea", emoji: "🇪🇷", year: 1993, type: "flag" },
        { name: "East Timor", emoji: "🇹🇱", year: 2002, type: "flag" },
        { name: "Kosovo", emoji: "🇽🇰", year: 2008, type: "flag" },
        { name: "Montenegro", emoji: "🇲🇪", year: 2006, type: "flag" },
        { name: "Albania", emoji: "🇦🇱", year: 1912, type: "flag" },
        { name: "Andorra", emoji: "🇦🇩", year: 1278, type: "flag" },
        { name: "Angola", emoji: "🇦🇴", year: 1975, type: "flag" },
        { name: "Antigua and Barbuda", emoji: "🇦🇬", year: 1981, type: "flag" },
        { name: "Armenia", emoji: "🇦🇲", year: 1991, type: "flag" },
        { name: "Azerbaijan", emoji: "🇦🇿", year: 1991, type: "flag" },
        { name: "Bahamas", emoji: "🇧🇸", year: 1973, type: "flag" },
        { name: "Barbados", emoji: "🇧🇧", year: 1966, type: "flag" },
        { name: "Belarus", emoji: "🇧🇾", year: 1991, type: "flag" },
        { name: "Belize", emoji: "🇧🇿", year: 1981, type: "flag" },
        { name: "Benin", emoji: "🇧🇯", year: 1960, type: "flag" },
        { name: "Bhutan", emoji: "🇧🇹", year: 1949, type: "flag" },
        { name: "Bosnia and Herzegovina", emoji: "🇧🇦", year: 1992, type: "flag" },
        { name: "Botswana", emoji: "🇧🇼", year: 1966, type: "flag" },
        { name: "Brunei", emoji: "🇧🇳", year: 1984, type: "flag" },
        { name: "Bulgaria", emoji: "🇧🇬", year: 1908, type: "flag" },
        { name: "Burkina Faso", emoji: "🇧🇫", year: 1960, type: "flag" },
        { name: "Burundi", emoji: "🇧🇮", year: 1962, type: "flag" },
        { name: "Cabo Verde", emoji: "🇨🇻", year: 1975, type: "flag" },
        { name: "Cameroon", emoji: "🇨🇲", year: 1960, type: "flag" },
        { name: "Central African Republic", emoji: "🇨🇫", year: 1960, type: "flag" },
        { name: "Chad", emoji: "🇹🇩", year: 1960, type: "flag" },
        { name: "Comoros", emoji: "🇰🇲", year: 1975, type: "flag" },
        { name: "Congo (Republic)", emoji: "🇨🇬", year: 1960, type: "flag" },
        { name: "Cyprus", emoji: "🇨🇾", year: 1960, type: "flag" },
        { name: "Djibouti", emoji: "🇩🇯", year: 1977, type: "flag" },
        { name: "Dominica", emoji: "🇩🇲", year: 1978, type: "flag" },
        { name: "El Salvador", emoji: "🇸🇻", year: 1821, type: "flag" },
        { name: "Equatorial Guinea", emoji: "🇬🇶", year: 1968, type: "flag" },
        { name: "Eswatini", emoji: "🇸🇿", year: 1968, type: "flag" },
        { name: "Fiji", emoji: "🇫🇯", year: 1970, type: "flag" },
        { name: "Gabon", emoji: "🇬🇦", year: 1960, type: "flag" },
        { name: "Gambia", emoji: "🇬🇲", year: 1965, type: "flag" },
        { name: "Georgia", emoji: "🇬🇪", year: 1991, type: "flag" },
        { name: "Grenada", emoji: "🇬🇩", year: 1974, type: "flag" },
        { name: "Guatemala", emoji: "🇬🇹", year: 1821, type: "flag" },
        { name: "Guinea", emoji: "🇬🇳", year: 1958, type: "flag" },
        { name: "Guinea-Bissau", emoji: "🇬🇼", year: 1973, type: "flag" },
        { name: "Guyana", emoji: "🇬🇾", year: 1966, type: "flag" },
        { name: "Honduras", emoji: "🇭🇳", year: 1821, type: "flag" },
        { name: "Ivory Coast", emoji: "🇨🇮", year: 1960, type: "flag" },
        { name: "Kazakhstan", emoji: "🇰🇿", year: 1991, type: "flag" },
        { name: "Kiribati", emoji: "🇰🇮", year: 1979, type: "flag" },
        { name: "Kyrgyzstan", emoji: "🇰🇬", year: 1991, type: "flag" },
        { name: "Latvia", emoji: "🇱🇻", year: 1918, type: "flag" },
        { name: "Lesotho", emoji: "🇱🇸", year: 1966, type: "flag" },
        { name: "Liberia", emoji: "🇱🇷", year: 1847, type: "flag" },
        { name: "Liechtenstein", emoji: "🇱🇮", year: 1719, type: "flag" },
        { name: "Lithuania", emoji: "🇱🇹", year: 1918, type: "flag" },
        { name: "Luxembourg", emoji: "🇱🇺", year: 1839, type: "flag" },
        { name: "Madagascar", emoji: "🇲🇬", year: 1960, type: "flag" },
        { name: "Malawi", emoji: "🇲🇼", year: 1964, type: "flag" },
        { name: "Maldives", emoji: "🇲🇻", year: 1965, type: "flag" },
        { name: "Mali", emoji: "🇲🇱", year: 1960, type: "flag" },
        { name: "Malta", emoji: "🇲🇹", year: 1964, type: "flag" },
        { name: "Marshall Islands", emoji: "🇲🇭", year: 1986, type: "flag" },
        { name: "Mauritania", emoji: "🇲🇷", year: 1960, type: "flag" },
        { name: "Mauritius", emoji: "🇲🇺", year: 1968, type: "flag" },
        { name: "Micronesia", emoji: "🇫🇲", year: 1986, type: "flag" },
        { name: "Moldova", emoji: "🇲🇩", year: 1991, type: "flag" },
        { name: "Monaco", emoji: "🇲🇨", year: 1297, type: "flag" },
        { name: "Nicaragua", emoji: "🇳🇮", year: 1821, type: "flag" },
        { name: "Niger", emoji: "🇳🇪", year: 1960, type: "flag" },
        { name: "North Macedonia", emoji: "🇲🇰", year: 1991, type: "flag" },
        { name: "Palau", emoji: "🇵🇼", year: 1994, type: "flag" },
        { name: "Palestine", emoji: "🇵🇸", year: 1988, type: "flag" },
        { name: "Papua New Guinea", emoji: "🇵🇬", year: 1975, type: "flag" },
        { name: "Rwanda", emoji: "🇷🇼", year: 1962, type: "flag" },
        { name: "Saint Kitts and Nevis", emoji: "🇰🇳", year: 1983, type: "flag" },
        { name: "Saint Lucia", emoji: "🇱🇨", year: 1979, type: "flag" },
        { name: "Saint Vincent and the Grenadines", emoji: "🇻🇨", year: 1979, type: "flag" },
        { name: "Samoa", emoji: "🇼🇸", year: 1962, type: "flag" },
        { name: "San Marino", emoji: "🇸🇲", year: 301, type: "flag" },
        { name: "Sao Tome and Principe", emoji: "🇸🇹", year: 1975, type: "flag" },
        { name: "Senegal", emoji: "🇸🇳", year: 1960, type: "flag" },
        { name: "Seychelles", emoji: "🇸🇨", year: 1976, type: "flag" },
        { name: "Sierra Leone", emoji: "🇸🇱", year: 1961, type: "flag" },
        { name: "Slovakia", emoji: "🇸🇰", year: 1993, type: "flag" },
        { name: "Slovenia", emoji: "🇸🇮", year: 1991, type: "flag" },
        { name: "Solomon Islands", emoji: "🇸🇧", year: 1978, type: "flag" },
        { name: "Somalia", emoji: "🇸🇴", year: 1960, type: "flag" },
        { name: "Sudan", emoji: "🇸🇩", year: 1956, type: "flag" },
        { name: "Suriname", emoji: "🇸🇷", year: 1975, type: "flag" },
        { name: "Syria", emoji: "🇸🇾", year: 1946, type: "flag" },
        { name: "Taiwan", emoji: "🇹🇼", year: 1949, type: "flag" },
        { name: "Tajikistan", emoji: "🇹🇯", year: 1991, type: "flag" },
        { name: "Togo", emoji: "🇹🇬", year: 1960, type: "flag" },
        { name: "Tonga", emoji: "🇹🇴", year: 1970, type: "flag" },
        { name: "Trinidad and Tobago", emoji: "🇹🇹", year: 1962, type: "flag" },
        { name: "Turkmenistan", emoji: "🇹🇲", year: 1991, type: "flag" },
        { name: "Tuvalu", emoji: "🇹🇻", year: 1978, type: "flag" },
        { name: "Uganda", emoji: "🇺🇬", year: 1962, type: "flag" },
        { name: "Uzbekistan", emoji: "🇺🇿", year: 1991, type: "flag" },
        { name: "Vanuatu", emoji: "🇻🇺", year: 1980, type: "flag" },
        { name: "Vatican City", emoji: "🇻🇦", year: 1929, type: "flag" },
        { name: "Yemen", emoji: "🇾🇪", year: 1990, type: "flag" },
        { name: "Zambia", emoji: "🇿🇲", year: 1964, type: "flag" },

        // === LANDMARKS ===
        { name: "Great Pyramid of Giza", emoji: "🔺", year: -2560, type: "landmark", desc: "Ancient tomb in Egypt" },
        { name: "Stonehenge", emoji: "🪨", year: -3000, type: "landmark", desc: "Prehistoric stone circle in England" },
        { name: "Parthenon", emoji: "🏛️", year: -432, type: "landmark", desc: "Temple in Athens" },
        { name: "Colosseum", emoji: "🏟️", year: 80, type: "landmark", desc: "Amphitheatre in Rome" },
        { name: "Hagia Sophia", emoji: "🕌", year: 537, type: "landmark", desc: "Cathedral turned mosque in Istanbul" },
        { name: "Angkor Wat", emoji: "🛕", year: 1150, type: "landmark", desc: "Largest religious monument" },
        { name: "Notre-Dame Cathedral", emoji: "⛪", year: 1345, type: "landmark", desc: "Gothic cathedral in Paris" },
        { name: "Leaning Tower of Pisa", emoji: "🏗️", year: 1372, type: "landmark", desc: "Famous tilted tower in Italy" },
        { name: "Machu Picchu", emoji: "🏔️", year: 1450, type: "landmark", desc: "Inca citadel in Peru" },
        { name: "Taj Mahal", emoji: "🕌", year: 1653, type: "landmark", desc: "Marble mausoleum in India" },
        { name: "Statue of Liberty", emoji: "🗽", year: 1886, type: "landmark", desc: "Iconic statue in New York" },
        { name: "Eiffel Tower", emoji: "🗼", year: 1889, type: "landmark", desc: "Iron tower in Paris" },
        { name: "Empire State Building", emoji: "🏙️", year: 1931, type: "landmark", desc: "Skyscraper in New York" },
        { name: "Golden Gate Bridge", emoji: "🌉", year: 1937, type: "landmark", desc: "Bridge in San Francisco" },
        { name: "Sydney Opera House", emoji: "🎭", year: 1973, type: "landmark", desc: "Performing arts center in Australia" },
        { name: "Burj Khalifa", emoji: "🏗️", year: 2010, type: "landmark", desc: "Tallest building in the world" },
        { name: "Great Wall of China", emoji: "🧱", year: -700, type: "landmark", desc: "Fortification across China" },
        { name: "Petra", emoji: "🏜️", year: -312, type: "landmark", desc: "City carved in rock, Jordan" },
        { name: "Chichen Itza", emoji: "🏛️", year: 600, type: "landmark", desc: "Mayan pyramid in Mexico" },
        { name: "Christ the Redeemer", emoji: "✝️", year: 1931, type: "landmark", desc: "Statue in Rio de Janeiro" },

        // === HISTORICAL EVENTS ===
        { name: "Invention of Writing", emoji: "📜", year: -3200, type: "history", desc: "Cuneiform in Mesopotamia" },
        { name: "Founding of Rome", emoji: "🐺", year: -753, type: "history", desc: "Traditional founding by Romulus" },
        { name: "Fall of Rome", emoji: "⚔️", year: 476, type: "history", desc: "Western Roman Empire collapsed" },
        { name: "Magna Carta Signed", emoji: "📜", year: 1215, type: "history", desc: "Foundation of constitutional law" },
        { name: "Renaissance Begins", emoji: "🎨", year: 1400, type: "history", desc: "Cultural rebirth in Italy" },
        { name: "Gutenberg Printing Press", emoji: "📰", year: 1440, type: "history", desc: "Revolutionized information spread" },
        { name: "Columbus Reaches America", emoji: "⛵", year: 1492, type: "history", desc: "European discovery of the New World" },
        { name: "Industrial Revolution", emoji: "🏭", year: 1760, type: "history", desc: "Transition to machine manufacturing" },
        { name: "French Revolution", emoji: "🔥", year: 1789, type: "history", desc: "Storming of the Bastille" },
        { name: "Suez Canal Opens", emoji: "⛴️", year: 1869, type: "history", desc: "Connecting Mediterranean and Red Sea" },
        { name: "First Olympic Games (Modern)", emoji: "🏅", year: 1896, type: "history", desc: "Revived in Athens" },
        { name: "Titanic Sinks", emoji: "🚢", year: 1912, type: "history", desc: "Unsinkable ship hits an iceberg" },
        { name: "World War I Begins", emoji: "💣", year: 1914, type: "history", desc: "The Great War erupts" },
        { name: "Panama Canal Opens", emoji: "🚢", year: 1914, type: "history", desc: "Connecting Atlantic and Pacific" },
        { name: "Women's Suffrage in US", emoji: "✊", year: 1920, type: "history", desc: "19th Amendment grants voting rights" },
        { name: "Discovery of Penicillin", emoji: "💊", year: 1928, type: "history", desc: "Alexander Fleming's breakthrough" },
        { name: "World War II Ends", emoji: "🕊️", year: 1945, type: "history", desc: "Allied victory, end of global conflict" },
        { name: "Mount Everest First Summit", emoji: "⛰️", year: 1953, type: "history", desc: "Hillary and Tenzing reach the top" },
        { name: "DNA Structure Discovered", emoji: "🧬", year: 1953, type: "history", desc: "Watson and Crick's double helix" },
        { name: "First Moon Landing", emoji: "🌙", year: 1969, type: "history", desc: "Neil Armstrong walks on the Moon" },
        { name: "Fall of the Berlin Wall", emoji: "🧱", year: 1989, type: "history", desc: "Symbolic end of the Cold War" },
        { name: "Nelson Mandela Freed", emoji: "✊", year: 1990, type: "history", desc: "Released after 27 years in prison" },
        { name: "Internet Goes Public", emoji: "🌐", year: 1991, type: "history", desc: "World Wide Web becomes accessible" },
        { name: "First iPhone Released", emoji: "📱", year: 2007, type: "history", desc: "Apple revolutionized smartphones" },
        { name: "COVID-19 Pandemic", emoji: "😷", year: 2020, type: "history", desc: "Global pandemic changes the world" },
    
];

module.exports = { ALL_CARDS };
