const ALL_CARDS = [

        // === FLAGS (no country name shown, no "from X" hints) ===
        { name: "United States", name_he: "ארצות הברית", emoji: "🇺🇸", year: 1776, type: "flag" },
        { name: "France", name_he: "צרפת", emoji: "🇫🇷", year: 1794, type: "flag" },
        { name: "Brazil", name_he: "ברזיל", emoji: "🇧🇷", year: 1822, type: "flag" },
        { name: "Italy", name_he: "איטליה", emoji: "🇮🇹", year: 1861, type: "flag" },
        { name: "Germany", name_he: "גרמניה", emoji: "🇩🇪", year: 1871, type: "flag" },
        { name: "Australia", name_he: "אוסטרליה", emoji: "🇦🇺", year: 1901, type: "flag" },
        { name: "Israel", name_he: "ישראל", emoji: "🇮🇱", year: 1948, type: "flag" },
        { name: "India", name_he: "הודו", emoji: "🇮🇳", year: 1947, type: "flag" },
        { name: "South Sudan", name_he: "דרום סודן", emoji: "🇸🇸", year: 2011, type: "flag" },
        { name: "Pakistan", name_he: "פקיסטן", emoji: "🇵🇰", year: 1947, type: "flag" },
        { name: "South Africa", name_he: "דרום אפריקה", emoji: "🇿🇦", year: 1994, type: "flag" },
        { name: "Japan", name_he: "יפן", emoji: "🇯🇵", year: 1870, type: "flag" },
        { name: "Mexico", name_he: "מקסיקו", emoji: "🇲🇽", year: 1821, type: "flag" },
        { name: "Greece", name_he: "יוון", emoji: "🇬🇷", year: 1829, type: "flag" },
        { name: "Canada", name_he: "קנדה", emoji: "🇨🇦", year: 1965, type: "flag" },
        { name: "China", name_he: "סין", emoji: "🇨🇳", year: 1949, type: "flag" },
        { name: "Russia", name_he: "רוסיה", emoji: "🇷🇺", year: 1991, type: "flag" },
        { name: "Turkey", name_he: "טורקיה", emoji: "🇹🇷", year: 1923, type: "flag" },
        { name: "Argentina", name_he: "ארגנטינה", emoji: "🇦🇷", year: 1816, type: "flag" },
        { name: "Nigeria", name_he: "ניגריה", emoji: "🇳🇬", year: 1960, type: "flag" },
        { name: "Indonesia", name_he: "אינדונזיה", emoji: "🇮🇩", year: 1945, type: "flag" },
        { name: "South Korea", name_he: "דרום קוריאה", emoji: "🇰🇷", year: 1948, type: "flag" },
        { name: "Ireland", name_he: "אירלנד", emoji: "🇮🇪", year: 1922, type: "flag" },
        { name: "Egypt", name_he: "מצרים", emoji: "🇪🇬", year: 1984, type: "flag" },
        { name: "Norway", name_he: "נורווגיה", emoji: "🇳🇴", year: 1905, type: "flag" },
        { name: "Poland", name_he: "פולין", emoji: "🇵🇱", year: 1918, type: "flag" },
        { name: "Colombia", name_he: "קולומביה", emoji: "🇨🇴", year: 1810, type: "flag" },
        { name: "Thailand", name_he: "תאילנד", emoji: "🇹🇭", year: 1917, type: "flag" },
        { name: "Vietnam", name_he: "וייטנאם", emoji: "🇻🇳", year: 1945, type: "flag" },
        { name: "Kenya", name_he: "קניה", emoji: "🇰🇪", year: 1963, type: "flag" },
        { name: "Ukraine", name_he: "אוקראינה", emoji: "🇺🇦", year: 1991, type: "flag" },
        { name: "Chile", name_he: "צ׳ילה", emoji: "🇨🇱", year: 1818, type: "flag" },
        { name: "Saudi Arabia", name_he: "ערב הסעודית", emoji: "🇸🇦", year: 1932, type: "flag" },
        { name: "Jamaica", name_he: "ג׳מייקה", emoji: "🇯🇲", year: 1962, type: "flag" },
        { name: "Nepal", name_he: "נפאל", emoji: "🇳🇵", year: 1962, type: "flag" },
        { name: "Cuba", name_he: "קובה", emoji: "🇨🇺", year: 1902, type: "flag" },
        { name: "Ethiopia", name_he: "אתיופיה", emoji: "🇪🇹", year: 1897, type: "flag" },
        { name: "UAE", name_he: "איחוד האמירויות", emoji: "🇦🇪", year: 1971, type: "flag" },
        { name: "Switzerland", name_he: "שווייץ", emoji: "🇨🇭", year: 1848, type: "flag" },
        { name: "Denmark", name_he: "דנמרק", emoji: "🇩🇰", year: 1219, type: "flag" },
        { name: "United Kingdom", name_he: "בריטניה", emoji: "🇬🇧", year: 1801, type: "flag" },
        { name: "Spain", name_he: "ספרד", emoji: "🇪🇸", year: 1981, type: "flag" },
        { name: "Portugal", name_he: "פורטוגל", emoji: "🇵🇹", year: 1910, type: "flag" },
        { name: "Sweden", name_he: "שוודיה", emoji: "🇸🇪", year: 1906, type: "flag" },
        { name: "Finland", name_he: "פינלנד", emoji: "🇫🇮", year: 1917, type: "flag" },
        { name: "Belgium", name_he: "בלגיה", emoji: "🇧🇪", year: 1830, type: "flag" },
        { name: "Netherlands", name_he: "הולנד", emoji: "🇳🇱", year: 1815, type: "flag" },
        { name: "Austria", name_he: "אוסטריה", emoji: "🇦🇹", year: 1230, type: "flag" },
        { name: "Czech Republic", name_he: "צ׳כיה", emoji: "🇨🇿", year: 1993, type: "flag" },
        { name: "Romania", name_he: "רומניה", emoji: "🇷🇴", year: 1848, type: "flag" },
        { name: "Hungary", name_he: "הונגריה", emoji: "🇭🇺", year: 1918, type: "flag" },
        { name: "Croatia", name_he: "קרואטיה", emoji: "🇭🇷", year: 1991, type: "flag" },
        { name: "Serbia", name_he: "סרביה", emoji: "🇷🇸", year: 2006, type: "flag" },
        { name: "Iceland", name_he: "איסלנד", emoji: "🇮🇸", year: 1944, type: "flag" },
        { name: "New Zealand", name_he: "ניו זילנד", emoji: "🇳🇿", year: 1907, type: "flag" },
        { name: "Philippines", name_he: "הפיליפינים", emoji: "🇵🇭", year: 1898, type: "flag" },
        { name: "Malaysia", name_he: "מלזיה", emoji: "🇲🇾", year: 1963, type: "flag" },
        { name: "Singapore", name_he: "סינגפור", emoji: "🇸🇬", year: 1965, type: "flag" },
        { name: "Bangladesh", name_he: "בנגלדש", emoji: "🇧🇩", year: 1971, type: "flag" },
        { name: "Peru", name_he: "פרו", emoji: "🇵🇪", year: 1821, type: "flag" },
        { name: "Venezuela", name_he: "ונצואלה", emoji: "🇻🇪", year: 1811, type: "flag" },
        { name: "Ecuador", name_he: "אקוודור", emoji: "🇪🇨", year: 1830, type: "flag" },
        { name: "Morocco", name_he: "מרוקו", emoji: "🇲🇦", year: 1956, type: "flag" },
        { name: "Tunisia", name_he: "תוניסיה", emoji: "🇹🇳", year: 1956, type: "flag" },
        { name: "Algeria", name_he: "אלג׳יריה", emoji: "🇩🇿", year: 1962, type: "flag" },
        { name: "Ghana", name_he: "גאנה", emoji: "🇬🇭", year: 1957, type: "flag" },
        { name: "Tanzania", name_he: "טנזניה", emoji: "🇹🇿", year: 1964, type: "flag" },
        { name: "Libya", name_he: "לוב", emoji: "🇱🇾", year: 2011, type: "flag" },
        { name: "Iraq", name_he: "עיראק", emoji: "🇮🇶", year: 1932, type: "flag" },
        { name: "Iran", name_he: "איראן", emoji: "🇮🇷", year: 1980, type: "flag" },
        { name: "Jordan", name_he: "ירדן", emoji: "🇯🇴", year: 1946, type: "flag" },
        { name: "Lebanon", name_he: "לבנון", emoji: "🇱🇧", year: 1943, type: "flag" },
        { name: "Qatar", name_he: "קטאר", emoji: "🇶🇦", year: 1971, type: "flag" },
        { name: "Bahrain", name_he: "בחריין", emoji: "🇧🇭", year: 1971, type: "flag" },
        { name: "Kuwait", name_he: "כווית", emoji: "🇰🇼", year: 1961, type: "flag" },
        { name: "Oman", name_he: "עומאן", emoji: "🇴🇲", year: 1970, type: "flag" },
        { name: "Panama", name_he: "פנמה", emoji: "🇵🇦", year: 1903, type: "flag" },
        { name: "Costa Rica", name_he: "קוסטה ריקה", emoji: "🇨🇷", year: 1821, type: "flag" },
        { name: "Dominican Republic", name_he: "הרפובליקה הדומיניקנית", emoji: "🇩🇴", year: 1844, type: "flag" },
        { name: "Haiti", name_he: "האיטי", emoji: "🇭🇹", year: 1804, type: "flag" },
        { name: "Bolivia", name_he: "בוליביה", emoji: "🇧🇴", year: 1825, type: "flag" },
        { name: "Paraguay", name_he: "פרגוואי", emoji: "🇵🇾", year: 1811, type: "flag" },
        { name: "Uruguay", name_he: "אורוגוואי", emoji: "🇺🇾", year: 1825, type: "flag" },
        { name: "Sri Lanka", name_he: "סרי לנקה", emoji: "🇱🇰", year: 1948, type: "flag" },
        { name: "Myanmar", name_he: "מיאנמר", emoji: "🇲🇲", year: 2010, type: "flag" },
        { name: "Cambodia", name_he: "קמבודיה", emoji: "🇰🇭", year: 1953, type: "flag" },
        { name: "Laos", name_he: "לאוס", emoji: "🇱🇦", year: 1975, type: "flag" },
        { name: "Mongolia", name_he: "מונגוליה", emoji: "🇲🇳", year: 1911, type: "flag" },
        { name: "North Korea", name_he: "צפון קוריאה", emoji: "🇰🇵", year: 1948, type: "flag" },
        { name: "Afghanistan", name_he: "אפגניסטן", emoji: "🇦🇫", year: 1919, type: "flag" },
        { name: "Congo (DRC)", name_he: "קונגו (הרפובליקה הדמוקרטית)", emoji: "🇨🇩", year: 1960, type: "flag" },
        { name: "Mozambique", name_he: "מוזמביק", emoji: "🇲🇿", year: 1975, type: "flag" },
        { name: "Zimbabwe", name_he: "זימבבואה", emoji: "🇿🇼", year: 1980, type: "flag" },
        { name: "Namibia", name_he: "נמיביה", emoji: "🇳🇦", year: 1990, type: "flag" },
        { name: "Eritrea", name_he: "אריתריאה", emoji: "🇪🇷", year: 1993, type: "flag" },
        { name: "East Timor", name_he: "מזרח טימור", emoji: "🇹🇱", year: 2002, type: "flag" },
        { name: "Kosovo", name_he: "קוסובו", emoji: "🇽🇰", year: 2008, type: "flag" },
        { name: "Montenegro", name_he: "מונטנגרו", emoji: "🇲🇪", year: 2006, type: "flag" },
        { name: "Albania", name_he: "אלבניה", emoji: "🇦🇱", year: 1912, type: "flag" },
        { name: "Andorra", name_he: "אנדורה", emoji: "🇦🇩", year: 1278, type: "flag" },
        { name: "Angola", name_he: "אנגולה", emoji: "🇦🇴", year: 1975, type: "flag" },
        { name: "Antigua and Barbuda", name_he: "אנטיגואה וברבודה", emoji: "🇦🇬", year: 1981, type: "flag" },
        { name: "Armenia", name_he: "ארמניה", emoji: "🇦🇲", year: 1991, type: "flag" },
        { name: "Azerbaijan", name_he: "אזרבייג׳ן", emoji: "🇦🇿", year: 1991, type: "flag" },
        { name: "Bahamas", name_he: "איי בהאמה", emoji: "🇧🇸", year: 1973, type: "flag" },
        { name: "Barbados", name_he: "ברבדוס", emoji: "🇧🇧", year: 1966, type: "flag" },
        { name: "Belarus", name_he: "בלארוס", emoji: "🇧🇾", year: 1991, type: "flag" },
        { name: "Belize", name_he: "בליז", emoji: "🇧🇿", year: 1981, type: "flag" },
        { name: "Benin", name_he: "בנין", emoji: "🇧🇯", year: 1960, type: "flag" },
        { name: "Bhutan", name_he: "בהוטן", emoji: "🇧🇹", year: 1949, type: "flag" },
        { name: "Bosnia and Herzegovina", name_he: "בוסניה והרצגובינה", emoji: "🇧🇦", year: 1992, type: "flag" },
        { name: "Botswana", name_he: "בוצוואנה", emoji: "🇧🇼", year: 1966, type: "flag" },
        { name: "Brunei", name_he: "ברוניי", emoji: "🇧🇳", year: 1984, type: "flag" },
        { name: "Bulgaria", name_he: "בולגריה", emoji: "🇧🇬", year: 1908, type: "flag" },
        { name: "Burkina Faso", name_he: "בורקינה פאסו", emoji: "🇧🇫", year: 1960, type: "flag" },
        { name: "Burundi", name_he: "בורונדי", emoji: "🇧🇮", year: 1962, type: "flag" },
        { name: "Cabo Verde", name_he: "כף ורדה", emoji: "🇨🇻", year: 1975, type: "flag" },
        { name: "Cameroon", name_he: "קמרון", emoji: "🇨🇲", year: 1960, type: "flag" },
        { name: "Central African Republic", name_he: "הרפובליקה המרכז-אפריקנית", emoji: "🇨🇫", year: 1960, type: "flag" },
        { name: "Chad", name_he: "צ׳אד", emoji: "🇹🇩", year: 1960, type: "flag" },
        { name: "Comoros", name_he: "קומורו", emoji: "🇰🇲", year: 1975, type: "flag" },
        { name: "Congo (Republic)", name_he: "קונגו (הרפובליקה)", emoji: "🇨🇬", year: 1960, type: "flag" },
        { name: "Cyprus", name_he: "קפריסין", emoji: "🇨🇾", year: 1960, type: "flag" },
        { name: "Djibouti", name_he: "ג׳יבוטי", emoji: "🇩🇯", year: 1977, type: "flag" },
        { name: "Dominica", name_he: "דומיניקה", emoji: "🇩🇲", year: 1978, type: "flag" },
        { name: "El Salvador", name_he: "אל סלבדור", emoji: "🇸🇻", year: 1821, type: "flag" },
        { name: "Equatorial Guinea", name_he: "גינאה המשוונית", emoji: "🇬🇶", year: 1968, type: "flag" },
        { name: "Eswatini", name_he: "אסוואטיני", emoji: "🇸🇿", year: 1968, type: "flag" },
        { name: "Fiji", name_he: "פיג׳י", emoji: "🇫🇯", year: 1970, type: "flag" },
        { name: "Gabon", name_he: "גבון", emoji: "🇬🇦", year: 1960, type: "flag" },
        { name: "Gambia", name_he: "גמביה", emoji: "🇬🇲", year: 1965, type: "flag" },
        { name: "Georgia", name_he: "גאורגיה", emoji: "🇬🇪", year: 1991, type: "flag" },
        { name: "Grenada", name_he: "גרנדה", emoji: "🇬🇩", year: 1974, type: "flag" },
        { name: "Guatemala", name_he: "גואטמלה", emoji: "🇬🇹", year: 1821, type: "flag" },
        { name: "Guinea", name_he: "גינאה", emoji: "🇬🇳", year: 1958, type: "flag" },
        { name: "Guinea-Bissau", name_he: "גינאה-ביסאו", emoji: "🇬🇼", year: 1973, type: "flag" },
        { name: "Guyana", name_he: "גיאנה", emoji: "🇬🇾", year: 1966, type: "flag" },
        { name: "Honduras", name_he: "הונדורס", emoji: "🇭🇳", year: 1821, type: "flag" },
        { name: "Ivory Coast (Cote d'Ivoire)", name_he: "חוף השנהב", emoji: "🇨🇮", year: 1960, type: "flag" },
        { name: "Kazakhstan", name_he: "קזחסטן", emoji: "🇰🇿", year: 1991, type: "flag" },
        { name: "Kiribati", name_he: "קיריבטי", emoji: "🇰🇮", year: 1979, type: "flag" },
        { name: "Kyrgyzstan", name_he: "קירגיזסטן", emoji: "🇰🇬", year: 1991, type: "flag" },
        { name: "Latvia", name_he: "לטביה", emoji: "🇱🇻", year: 1918, type: "flag" },
        { name: "Lesotho", name_he: "לסוטו", emoji: "🇱🇸", year: 1966, type: "flag" },
        { name: "Liberia", name_he: "ליבריה", emoji: "🇱🇷", year: 1847, type: "flag" },
        { name: "Liechtenstein", name_he: "ליכטנשטיין", emoji: "🇱🇮", year: 1719, type: "flag" },
        { name: "Lithuania", name_he: "ליטא", emoji: "🇱🇹", year: 1918, type: "flag" },
        { name: "Luxembourg", name_he: "לוקסמבורג", emoji: "🇱🇺", year: 1839, type: "flag" },
        { name: "Madagascar", name_he: "מדגסקר", emoji: "🇲🇬", year: 1960, type: "flag" },
        { name: "Malawi", name_he: "מלאווי", emoji: "🇲🇼", year: 1964, type: "flag" },
        { name: "Maldives", name_he: "האיים המלדיביים", emoji: "🇲🇻", year: 1965, type: "flag" },
        { name: "Mali", name_he: "מאלי", emoji: "🇲🇱", year: 1960, type: "flag" },
        { name: "Malta", name_he: "מלטה", emoji: "🇲🇹", year: 1964, type: "flag" },
        { name: "Marshall Islands", name_he: "איי מרשל", emoji: "🇲🇭", year: 1986, type: "flag" },
        { name: "Mauritania", name_he: "מאוריטניה", emoji: "🇲🇷", year: 1960, type: "flag" },
        { name: "Mauritius", name_he: "מאוריציוס", emoji: "🇲🇺", year: 1968, type: "flag" },
        { name: "Micronesia", name_he: "מיקרונזיה", emoji: "🇫🇲", year: 1986, type: "flag" },
        { name: "Moldova", name_he: "מולדובה", emoji: "🇲🇩", year: 1991, type: "flag" },
        { name: "Monaco", name_he: "מונקו", emoji: "🇲🇨", year: 1297, type: "flag" },
        { name: "Nicaragua", name_he: "ניקרגואה", emoji: "🇳🇮", year: 1821, type: "flag" },
        { name: "Niger", name_he: "ניז׳ר", emoji: "🇳🇪", year: 1960, type: "flag" },
        { name: "North Macedonia", name_he: "מקדוניה הצפונית", emoji: "🇲🇰", year: 1991, type: "flag" },
        { name: "Palau", name_he: "פלאו", emoji: "🇵🇼", year: 1994, type: "flag" },
        { name: "Palestine", name_he: "פלסטין", emoji: "🇵🇸", year: 1988, type: "flag" },
        { name: "Papua New Guinea", name_he: "פפואה גינאה החדשה", emoji: "🇵🇬", year: 1975, type: "flag" },
        { name: "Rwanda", name_he: "רואנדה", emoji: "🇷🇼", year: 1962, type: "flag" },
        { name: "Saint Kitts and Nevis", name_he: "סנט קיטס ונוויס", emoji: "🇰🇳", year: 1983, type: "flag" },
        { name: "Saint Lucia", name_he: "סנט לוסיה", emoji: "🇱🇨", year: 1979, type: "flag" },
        { name: "Saint Vincent and the Grenadines", name_he: "סנט וינסנט והגרנדינים", emoji: "🇻🇨", year: 1979, type: "flag" },
        { name: "Samoa", name_he: "סמואה", emoji: "🇼🇸", year: 1962, type: "flag" },
        { name: "San Marino", name_he: "סן מרינו", emoji: "🇸🇲", year: 301, type: "flag" },
        { name: "Sao Tome and Principe (Sao Tome)", name_he: "סאו טומה ופרינסיפה", emoji: "🇸🇹", year: 1975, type: "flag" },
        { name: "Senegal", name_he: "סנגל", emoji: "🇸🇳", year: 1960, type: "flag" },
        { name: "Seychelles", name_he: "סיישל", emoji: "🇸🇨", year: 1976, type: "flag" },
        { name: "Sierra Leone", name_he: "סיירה לאונה", emoji: "🇸🇱", year: 1961, type: "flag" },
        { name: "Slovakia", name_he: "סלובקיה", emoji: "🇸🇰", year: 1993, type: "flag" },
        { name: "Slovenia", name_he: "סלובניה", emoji: "🇸🇮", year: 1991, type: "flag" },
        { name: "Solomon Islands", name_he: "איי שלמה", emoji: "🇸🇧", year: 1978, type: "flag" },
        { name: "Somalia", name_he: "סומליה", emoji: "🇸🇴", year: 1960, type: "flag" },
        { name: "Sudan", name_he: "סודן", emoji: "🇸🇩", year: 1956, type: "flag" },
        { name: "Suriname", name_he: "סורינאם", emoji: "🇸🇷", year: 1975, type: "flag" },
        { name: "Syria", name_he: "סוריה", emoji: "🇸🇾", year: 1946, type: "flag" },
        { name: "Taiwan", name_he: "טייוואן", emoji: "🇹🇼", year: 1949, type: "flag" },
        { name: "Tajikistan", name_he: "טג׳יקיסטן", emoji: "🇹🇯", year: 1991, type: "flag" },
        { name: "Togo", name_he: "טוגו", emoji: "🇹🇬", year: 1960, type: "flag" },
        { name: "Tonga", name_he: "טונגה", emoji: "🇹🇴", year: 1970, type: "flag" },
        { name: "Trinidad and Tobago", name_he: "טרינידד וטובגו", emoji: "🇹🇹", year: 1962, type: "flag" },
        { name: "Turkmenistan", name_he: "טורקמניסטן", emoji: "🇹🇲", year: 1991, type: "flag" },
        { name: "Tuvalu", name_he: "טובאלו", emoji: "🇹🇻", year: 1978, type: "flag" },
        { name: "Uganda", name_he: "אוגנדה", emoji: "🇺🇬", year: 1962, type: "flag" },
        { name: "Uzbekistan", name_he: "אוזבקיסטן", emoji: "🇺🇿", year: 1991, type: "flag" },
        { name: "Vanuatu", name_he: "ונואטו", emoji: "🇻🇺", year: 1980, type: "flag" },
        { name: "Vatican City", name_he: "הוותיקן", emoji: "🇻🇦", year: 1929, type: "flag" },
        { name: "Yemen", name_he: "תימן", emoji: "🇾🇪", year: 1990, type: "flag" },
        { name: "Zambia", name_he: "זמביה", emoji: "🇿🇲", year: 1964, type: "flag" },

        // === LANDMARKS (existing + new) — now with lat, lng, wiki ===
        { name: "Great Pyramid of Giza", name_he: "הפירמידה הגדולה של גיזה", emoji: "🔺", year: -2560, type: "landmark", desc: "Ancient tomb in Egypt", desc_he: "קבר עתיק במצרים", difficulty: 1, lat: 29.9792, lng: 31.1342, wiki: "Great_Pyramid_of_Giza" },
        { name: "Stonehenge", name_he: "סטונהנג׳", emoji: "🪨", year: -3000, type: "landmark", desc: "Prehistoric stone circle in England", desc_he: "מעגל אבנים פרהיסטורי באנגליה", difficulty: 1, lat: 51.1789, lng: -1.8262, wiki: "Stonehenge" },
        { name: "Parthenon", name_he: "הפרתנון", emoji: "🏛️", year: -432, type: "landmark", desc: "Temple in Athens", desc_he: "מקדש באתונה", difficulty: 2, lat: 37.9715, lng: 23.7267, wiki: "Parthenon" },
        { name: "Colosseum", name_he: "הקולוסיאום", emoji: "🏟️", year: 80, type: "landmark", desc: "Amphitheatre in Rome", desc_he: "אמפיתיאטרון ברומא", difficulty: 1, lat: 41.8902, lng: 12.4922, wiki: "Colosseum" },
        { name: "Hagia Sophia", name_he: "איה סופיה", emoji: "🕌", year: 537, type: "landmark", desc: "Cathedral turned mosque in Istanbul", desc_he: "קתדרלה שהפכה למסגד באיסטנבול", difficulty: 2, lat: 41.0086, lng: 28.9802, wiki: "Hagia_Sophia" },
        { name: "Angkor Wat", name_he: "אנגקור ואט", emoji: "🛕", year: 1150, type: "landmark", desc: "Largest religious monument", desc_he: "המונומנט הדתי הגדול בעולם", difficulty: 2, lat: 13.4125, lng: 103.8670, wiki: "Angkor_Wat" },
        { name: "Notre-Dame Cathedral", name_he: "קתדרלת נוטרדאם", emoji: "⛪", year: 1345, type: "landmark", desc: "Gothic cathedral in Paris", desc_he: "קתדרלה גותית בפריז", difficulty: 1, lat: 48.8530, lng: 2.3499, wiki: "Notre-Dame_de_Paris" },
        { name: "Leaning Tower of Pisa", name_he: "מגדל פיזה הנטוי", emoji: "🏗️", year: 1372, type: "landmark", desc: "Famous tilted tower in Italy", desc_he: "מגדל נטוי מפורסם באיטליה", difficulty: 1, lat: 43.7230, lng: 10.3966, wiki: "Leaning_Tower_of_Pisa" },
        { name: "Machu Picchu", name_he: "מאצ׳ו פיצ׳ו", emoji: "🏔️", year: 1450, type: "landmark", desc: "Inca citadel in Peru", desc_he: "מצודת אינקה בפרו", difficulty: 1, lat: -13.1631, lng: -72.5450, wiki: "Machu_Picchu" },
        { name: "Taj Mahal", name_he: "טאג׳ מהאל", emoji: "🕌", year: 1653, type: "landmark", desc: "Marble mausoleum in India", desc_he: "מאוזוליאום שיש בהודו", difficulty: 1, lat: 27.1751, lng: 78.0421, wiki: "Taj_Mahal" },
        { name: "Statue of Liberty", name_he: "פסל החירות", emoji: "🗽", year: 1886, type: "landmark", desc: "Iconic statue in New York", desc_he: "פסל מפורסם בניו יורק", difficulty: 1, lat: 40.6892, lng: -74.0445, wiki: "Statue_of_Liberty" },
        { name: "Eiffel Tower", name_he: "מגדל אייפל", emoji: "🗼", year: 1889, type: "landmark", desc: "Iron tower in Paris", desc_he: "מגדל ברזל בפריז", difficulty: 1, lat: 48.8584, lng: 2.2945, wiki: "Eiffel_Tower" },
        { name: "Empire State Building", name_he: "בניין אמפייר סטייט", emoji: "🏙️", year: 1931, type: "landmark", desc: "Skyscraper in New York", desc_he: "גורד שחקים בניו יורק", difficulty: 1, lat: 40.7484, lng: -73.9857, wiki: "Empire_State_Building" },
        { name: "Golden Gate Bridge", name_he: "גשר שער הזהב", emoji: "🌉", year: 1937, type: "landmark", desc: "Bridge in San Francisco", desc_he: "גשר בסן פרנסיסקו", difficulty: 1, lat: 37.8199, lng: -122.4783, wiki: "Golden_Gate_Bridge" },
        { name: "Sydney Opera House", name_he: "בית האופרה של סידני", emoji: "🎭", year: 1973, type: "landmark", desc: "Performing arts center in Australia", desc_he: "מרכז אמנויות הבמה באוסטרליה", difficulty: 1, lat: -33.8568, lng: 151.2153, wiki: "Sydney_Opera_House" },
        { name: "Burj Khalifa", name_he: "בורג׳ ח׳ליפה", emoji: "🏗️", year: 2010, type: "landmark", desc: "Tallest building in the world", desc_he: "הבניין הגבוה בעולם", difficulty: 1, lat: 25.1972, lng: 55.2744, wiki: "Burj_Khalifa" },
        { name: "Great Wall of China", name_he: "החומה הסינית הגדולה", emoji: "🧱", year: -700, type: "landmark", desc: "Fortification across China", desc_he: "ביצור לאורך סין", difficulty: 1, lat: 40.4319, lng: 116.5704, wiki: "Great_Wall_of_China" },
        { name: "Petra", name_he: "פטרה", emoji: "🏜️", year: -312, type: "landmark", desc: "City carved in rock, Jordan", desc_he: "עיר חצובה בסלע בירדן", difficulty: 2, lat: 30.3285, lng: 35.4444, wiki: "Petra" },
        { name: "Chichen Itza", name_he: "צ׳יצ׳ן איצה", emoji: "🏛️", year: 600, type: "landmark", desc: "Mayan pyramid in Mexico", desc_he: "פירמידה של המאיה במקסיקו", difficulty: 2, lat: 20.6843, lng: -88.5678, wiki: "Chichen_Itza" },
        { name: "Christ the Redeemer", name_he: "ישו הגואל", emoji: "✝️", year: 1931, type: "landmark", desc: "Statue in Rio de Janeiro", desc_he: "פסל בריו דה ז׳נירו", difficulty: 1, lat: -22.9519, lng: -43.2105, wiki: "Christ_the_Redeemer_(statue)" },

        // --- NEW LANDMARKS (40) — with lat, lng, wiki ---
        { name: "Kremlin", name_he: "הקרמלין", emoji: "🏰", year: 1495, type: "landmark", desc: "Fortified complex in Moscow", desc_he: "מתחם מבוצר במוסקבה", difficulty: 1, lat: 55.7520, lng: 37.6175, wiki: "Moscow_Kremlin" },
        { name: "Big Ben", name_he: "ביג בן", emoji: "🕰️", year: 1859, type: "landmark", desc: "Clock tower in London", desc_he: "מגדל שעון בלונדון", difficulty: 1, lat: 51.5007, lng: -0.1246, wiki: "Big_Ben" },
        { name: "Sagrada Familia", name_he: "סגרדה פמיליה", emoji: "⛪", year: 1882, type: "landmark", desc: "Gaudi's basilica in Barcelona", desc_he: "הבזיליקה של גאודי בברצלונה", difficulty: 2, lat: 41.4036, lng: 2.1744, wiki: "Sagrada_Fam%C3%ADlia" },
        { name: "Forbidden City", name_he: "העיר האסורה", emoji: "🏯", year: 1420, type: "landmark", desc: "Imperial palace in Beijing", desc_he: "ארמון קיסרי בבייג׳ינג", difficulty: 2, lat: 39.9163, lng: 116.3972, wiki: "Forbidden_City" },
        { name: "Palace of Versailles", name_he: "ארמון ורסאי", emoji: "👑", year: 1682, type: "landmark", desc: "Royal palace near Paris", desc_he: "ארמון מלכותי ליד פריז", difficulty: 1, lat: 48.8049, lng: 2.1204, wiki: "Palace_of_Versailles" },
        { name: "Acropolis", name_he: "האקרופוליס", emoji: "🏛️", year: -447, type: "landmark", desc: "Citadel above Athens", desc_he: "מצודה מעל אתונה", difficulty: 2, lat: 37.9715, lng: 23.7257, wiki: "Acropolis_of_Athens" },
        { name: "Tower of London", name_he: "מגדל לונדון", emoji: "🏰", year: 1066, type: "landmark", desc: "Historic castle in London", desc_he: "טירה היסטורית בלונדון", difficulty: 1, lat: 51.5081, lng: -0.0759, wiki: "Tower_of_London" },
        { name: "Pompeii Ruins", name_he: "חורבות פומפיי", emoji: "🌋", year: -600, type: "landmark", desc: "Roman city buried by Vesuvius", desc_he: "עיר רומית שנקברה בהר געש", difficulty: 2, lat: 40.7488, lng: 14.4848, wiki: "Pompeii" },
        { name: "Easter Island Moai", name_he: "פסלי מואי באי הפסחא", emoji: "🗿", year: 1250, type: "landmark", desc: "Stone statues in Pacific Ocean", desc_he: "פסלי אבן באוקיינוס השקט", difficulty: 2, lat: -27.1127, lng: -109.3497, wiki: "Moai" },
        { name: "Mount Rushmore", name_he: "הר ראשמור", emoji: "⛰️", year: 1941, type: "landmark", desc: "Presidential faces carved in rock", desc_he: "פני נשיאים חצובים בסלע", difficulty: 1, lat: 43.8791, lng: -103.4591, wiki: "Mount_Rushmore" },
        { name: "Sistine Chapel", name_he: "הקפלה הסיסטינית", emoji: "🎨", year: 1512, type: "landmark", desc: "Michelangelo's ceiling in Vatican", desc_he: "תקרת מיכלאנג׳לו בוותיקן", difficulty: 2, lat: 41.9029, lng: 12.4545, wiki: "Sistine_Chapel" },
        { name: "Pantheon", name_he: "הפנתיאון", emoji: "🏛️", year: 125, type: "landmark", desc: "Ancient temple in Rome", desc_he: "מקדש עתיק ברומא", difficulty: 2, lat: 41.8986, lng: 12.4769, wiki: "Pantheon,_Rome" },
        { name: "Brandenburg Gate", name_he: "שער ברנדנבורג", emoji: "🚪", year: 1791, type: "landmark", desc: "Neoclassical gate in Berlin", desc_he: "שער ניאו-קלאסי בברלין", difficulty: 2, lat: 52.5163, lng: 13.3777, wiki: "Brandenburg_Gate" },
        { name: "Neuschwanstein Castle", name_he: "טירת נוישוונשטיין", emoji: "🏰", year: 1886, type: "landmark", desc: "Fairy-tale castle in Bavaria", desc_he: "טירת אגדות בבוואריה", difficulty: 2, lat: 47.5576, lng: 10.7498, wiki: "Neuschwanstein_Castle" },
        { name: "Alhambra", name_he: "אלהמברה", emoji: "🕌", year: 1238, type: "landmark", desc: "Moorish palace in Granada, Spain", desc_he: "ארמון מורי בגרנדה, ספרד", difficulty: 2, lat: 37.1761, lng: -3.5881, wiki: "Alhambra" },
        { name: "Blue Mosque", name_he: "המסגד הכחול", emoji: "🕌", year: 1616, type: "landmark", desc: "Ottoman mosque in Istanbul", desc_he: "מסגד עות׳מאני באיסטנבול", difficulty: 2, lat: 41.0054, lng: 28.9768, wiki: "Sultan_Ahmed_Mosque" },
        { name: "Western Wall", name_he: "הכותל המערבי", emoji: "🧱", year: -19, type: "landmark", desc: "Holy site in Jerusalem", desc_he: "אתר קדוש בירושלים", difficulty: 2, lat: 31.7767, lng: 35.2345, wiki: "Western_Wall" },
        { name: "Great Sphinx of Giza", name_he: "הספינקס הגדול של גיזה", emoji: "🦁", year: -2500, type: "landmark", desc: "Limestone statue in Egypt", desc_he: "פסל אבן גיר במצרים", difficulty: 1, lat: 29.9753, lng: 31.1376, wiki: "Great_Sphinx_of_Giza" },
        { name: "Abu Simbel", name_he: "אבו סימבל", emoji: "🏛️", year: -1264, type: "landmark", desc: "Rock temples in southern Egypt", desc_he: "מקדשי סלע בדרום מצרים", difficulty: 3, lat: 22.3360, lng: 31.6256, wiki: "Abu_Simbel" },
        { name: "Terracotta Army", name_he: "צבא החרס", emoji: "🪖", year: -210, type: "landmark", desc: "Clay soldiers in Xi'an, China", desc_he: "חיילי חרס בשיאן, סין", difficulty: 2, lat: 34.3848, lng: 109.2734, wiki: "Terracotta_Army" },
        { name: "Potala Palace", name_he: "ארמון פוטאלה", emoji: "🏯", year: 1649, type: "landmark", desc: "Dalai Lama's palace in Tibet", desc_he: "ארמון הדלאי לאמה בטיבט", difficulty: 3, lat: 29.6578, lng: 91.1170, wiki: "Potala_Palace" },
        { name: "Borobudur", name_he: "בורובודור", emoji: "🛕", year: 800, type: "landmark", desc: "Buddhist temple in Java", desc_he: "מקדש בודהיסטי בג׳אווה", difficulty: 3, lat: -7.6079, lng: 110.2038, wiki: "Borobudur" },
        { name: "Pyramids of Teotihuacan", name_he: "פירמידות טאוטיוואקן", emoji: "🔺", year: 200, type: "landmark", desc: "Ancient pyramids near Mexico City", desc_he: "פירמידות עתיקות ליד מקסיקו סיטי", difficulty: 3, lat: 19.6925, lng: -98.8438, wiki: "Teotihuacan" },
        { name: "Mesa Verde", name_he: "מסה ורדה", emoji: "🏚️", year: 1190, type: "landmark", desc: "Cliff dwellings in Colorado", desc_he: "מגורי צוק בקולורדו", difficulty: 3, lat: 37.1838, lng: -108.4887, wiki: "Mesa_Verde_National_Park" },
        { name: "Great Zimbabwe", name_he: "זימבבואה הגדולה", emoji: "🏰", year: 1100, type: "landmark", desc: "Medieval stone city in Africa", desc_he: "עיר אבן ימי-ביניימית באפריקה", difficulty: 3, lat: -20.2674, lng: 30.9338, wiki: "Great_Zimbabwe" },
        { name: "Timbuktu", name_he: "טימבוקטו", emoji: "🕌", year: 1100, type: "landmark", desc: "Ancient learning center in Mali", desc_he: "מרכז למידה עתיק במאלי", difficulty: 3, lat: 16.7735, lng: -3.0074, wiki: "Timbuktu" },
        { name: "Luxor Temple", name_he: "מקדש לוקסור", emoji: "🏛️", year: -1400, type: "landmark", desc: "Ancient temple complex in Egypt", desc_he: "מתחם מקדשים עתיק במצרים", difficulty: 3, lat: 25.6996, lng: 32.6390, wiki: "Luxor_Temple" },
        { name: "St. Basil's Cathedral", name_he: "קתדרלת ואסילי הקדוש", emoji: "⛪", year: 1561, type: "landmark", desc: "Colorful cathedral in Moscow", desc_he: "קתדרלה צבעונית במוסקבה", difficulty: 2, lat: 55.7525, lng: 37.6231, wiki: "Saint_Basil%27s_Cathedral" },
        { name: "Opera Garnier", name_he: "אופרה גרנייה", emoji: "🎭", year: 1875, type: "landmark", desc: "Opera house in Paris", desc_he: "בית אופרה בפריז", difficulty: 3, lat: 48.8720, lng: 2.3316, wiki: "Palais_Garnier" },
        { name: "Buckingham Palace", name_he: "ארמון בקינגהאם", emoji: "👑", year: 1703, type: "landmark", desc: "Royal residence in London", desc_he: "מעון מלכותי בלונדון", difficulty: 1, lat: 51.5014, lng: -0.1419, wiki: "Buckingham_Palace" },
        { name: "Reichstag Building", name_he: "בניין הרייכסטאג", emoji: "🏛️", year: 1894, type: "landmark", desc: "Parliament building in Berlin", desc_he: "בניין הפרלמנט בברלין", difficulty: 2, lat: 52.5186, lng: 13.3761, wiki: "Reichstag_building" },
        { name: "Tokyo Tower", name_he: "מגדל טוקיו", emoji: "🗼", year: 1958, type: "landmark", desc: "Broadcast tower in Tokyo", desc_he: "מגדל שידור בטוקיו", difficulty: 1, lat: 35.6586, lng: 139.7454, wiki: "Tokyo_Tower" },
        { name: "CN Tower", name_he: "מגדל CN", emoji: "🗼", year: 1976, type: "landmark", desc: "Communications tower in Toronto", desc_he: "מגדל תקשורת בטורונטו", difficulty: 2, lat: 43.6426, lng: -79.3871, wiki: "CN_Tower" },
        { name: "Space Needle", name_he: "מחט החלל", emoji: "🗼", year: 1962, type: "landmark", desc: "Observation tower in Seattle", desc_he: "מגדל תצפית בסיאטל", difficulty: 1, lat: 47.6205, lng: -122.3493, wiki: "Space_Needle" },
        { name: "Panama Canal", name_he: "תעלת פנמה", emoji: "🚢", year: 1914, type: "landmark", desc: "Waterway connecting two oceans", desc_he: "תעלה המחברת שני אוקיינוסים", difficulty: 1, lat: 9.0801, lng: -79.6813, wiki: "Panama_Canal" },
        { name: "Suez Canal", name_he: "תעלת סואץ", emoji: "⛴️", year: 1869, type: "landmark", desc: "Waterway connecting two seas", desc_he: "תעלה המחברת שני ימים", difficulty: 2, lat: 30.4574, lng: 32.3499, wiki: "Suez_Canal" },
        { name: "Petra Treasury", name_he: "האוצר בפטרה", emoji: "🏜️", year: -100, type: "landmark", desc: "Carved facade in Jordan", desc_he: "חזית חצובה בירדן", difficulty: 2, lat: 30.3223, lng: 35.4513, wiki: "Al-Khazneh" },
        { name: "Moai of Ahu Tongariki", name_he: "מואי של אהו טונגריקי", emoji: "🗿", year: 1450, type: "landmark", desc: "Largest moai platform on Easter Is.", desc_he: "במת המואי הגדולה באי הפסחא", difficulty: 3, lat: -27.1256, lng: -109.2770, wiki: "Ahu_Tongariki" },
        { name: "Persepolis", name_he: "פרסיפוליס", emoji: "🏛️", year: -515, type: "landmark", desc: "Ancient Persian capital ruins", desc_he: "חורבות בירת פרס העתיקה", difficulty: 3, lat: 29.9352, lng: 52.8914, wiki: "Persepolis" },
        { name: "Newgrange", name_he: "ניוגריינג׳", emoji: "🪨", year: -3200, type: "landmark", desc: "Prehistoric tomb in Ireland", desc_he: "קבר פרהיסטורי באירלנד", difficulty: 3, lat: 53.6947, lng: -6.4754, wiki: "Newgrange" },

        // === CITIES (50) ===
        { name: "Paris", name_he: "פריז", emoji: "🗼", lat: 48.8566, lng: 2.3522, type: "city", wiki: "Paris", difficulty: 1 },
        { name: "London", name_he: "לונדון", emoji: "💂", lat: 51.5074, lng: -0.1278, type: "city", wiki: "London", difficulty: 1 },
        { name: "Tokyo", name_he: "טוקיו", emoji: "🗾", lat: 35.6762, lng: 139.6503, type: "city", wiki: "Tokyo", difficulty: 1 },
        { name: "New York", name_he: "ניו יורק", emoji: "🗽", lat: 40.7128, lng: -74.0060, type: "city", wiki: "New_York_City", difficulty: 1 },
        { name: "Rome", name_he: "רומא", emoji: "🏛️", lat: 41.9028, lng: 12.4964, type: "city", wiki: "Rome", difficulty: 1 },
        { name: "Cairo", name_he: "קהיר", emoji: "🐫", lat: 30.0444, lng: 31.2357, type: "city", wiki: "Cairo", difficulty: 1 },
        { name: "Sydney", name_he: "סידני", emoji: "🦘", lat: -33.8688, lng: 151.2093, type: "city", wiki: "Sydney", difficulty: 1 },
        { name: "Rio de Janeiro", name_he: "ריו דה ז׳נירו", emoji: "🎭", lat: -22.9068, lng: -43.1729, type: "city", wiki: "Rio_de_Janeiro", difficulty: 1 },
        { name: "Beijing", name_he: "בייג׳ינג", emoji: "🏯", lat: 39.9042, lng: 116.4074, type: "city", wiki: "Beijing", difficulty: 1 },
        { name: "Moscow", name_he: "מוסקבה", emoji: "🏰", lat: 55.7558, lng: 37.6173, type: "city", wiki: "Moscow", difficulty: 1 },
        { name: "Dubai", name_he: "דובאי", emoji: "🏗️", lat: 25.2048, lng: 55.2708, type: "city", wiki: "Dubai", difficulty: 1 },
        { name: "Istanbul", name_he: "איסטנבול", emoji: "🕌", lat: 41.0082, lng: 28.9784, type: "city", wiki: "Istanbul", difficulty: 1 },
        { name: "Bangkok", name_he: "בנגקוק", emoji: "🛕", lat: 13.7563, lng: 100.5018, type: "city", wiki: "Bangkok", difficulty: 1 },
        { name: "Mumbai", name_he: "מומבאי", emoji: "🎬", lat: 19.0760, lng: 72.8777, type: "city", wiki: "Mumbai", difficulty: 1 },
        { name: "Berlin", name_he: "ברלין", emoji: "🐻", lat: 52.5200, lng: 13.4050, type: "city", wiki: "Berlin", difficulty: 1 },
        { name: "Barcelona", name_he: "ברצלונה", emoji: "⚽", lat: 41.3874, lng: 2.1686, type: "city", wiki: "Barcelona", difficulty: 1 },
        { name: "Amsterdam", name_he: "אמסטרדם", emoji: "🌷", lat: 52.3676, lng: 4.9041, type: "city", wiki: "Amsterdam", difficulty: 1 },
        { name: "San Francisco", name_he: "סן פרנסיסקו", emoji: "🌉", lat: 37.7749, lng: -122.4194, type: "city", wiki: "San_Francisco", difficulty: 1 },
        { name: "Toronto", name_he: "טורונטו", emoji: "🍁", lat: 43.6532, lng: -79.3832, type: "city", wiki: "Toronto", difficulty: 1 },
        { name: "Mexico City", name_he: "מקסיקו סיטי", emoji: "🌮", lat: 19.4326, lng: -99.1332, type: "city", wiki: "Mexico_City", difficulty: 1 },
        { name: "Buenos Aires", name_he: "בואנוס איירס", emoji: "💃", lat: -34.6037, lng: -58.3816, type: "city", wiki: "Buenos_Aires", difficulty: 1 },
        { name: "Seoul", name_he: "סיאול", emoji: "🇰🇷", lat: 37.5665, lng: 126.9780, type: "city", wiki: "Seoul", difficulty: 1 },
        { name: "Singapore", name_he: "סינגפור", emoji: "🦁", lat: 1.3521, lng: 103.8198, type: "city", wiki: "Singapore", difficulty: 1 },
        { name: "Hong Kong", name_he: "הונג קונג", emoji: "🏙️", lat: 22.3193, lng: 114.1694, type: "city", wiki: "Hong_Kong", difficulty: 1 },
        { name: "Nairobi", name_he: "ניירובי", emoji: "🦁", lat: -1.2921, lng: 36.8219, type: "city", wiki: "Nairobi", difficulty: 2 },
        { name: "Cape Town", name_he: "קייפטאון", emoji: "🏔️", lat: -33.9249, lng: 18.4241, type: "city", wiki: "Cape_Town", difficulty: 1 },
        { name: "Lagos", name_he: "לאגוס", emoji: "🌍", lat: 6.5244, lng: 3.3792, type: "city", wiki: "Lagos", difficulty: 2 },
        { name: "Marrakech", name_he: "מרקש", emoji: "🕌", lat: 31.6295, lng: -7.9811, type: "city", wiki: "Marrakech", difficulty: 2 },
        { name: "Jerusalem", name_he: "ירושלים", emoji: "✡️", lat: 31.7683, lng: 35.2137, type: "city", wiki: "Jerusalem", difficulty: 1 },
        { name: "Athens", name_he: "אתונה", emoji: "🏛️", lat: 37.9838, lng: 23.7275, type: "city", wiki: "Athens", difficulty: 1 },
        { name: "Vienna", name_he: "וינה", emoji: "🎻", lat: 48.2082, lng: 16.3738, type: "city", wiki: "Vienna", difficulty: 1 },
        { name: "Prague", name_he: "פראג", emoji: "🏰", lat: 50.0755, lng: 14.4378, type: "city", wiki: "Prague", difficulty: 1 },
        { name: "Stockholm", name_he: "שטוקהולם", emoji: "👑", lat: 59.3293, lng: 18.0686, type: "city", wiki: "Stockholm", difficulty: 1 },
        { name: "Dublin", name_he: "דבלין", emoji: "☘️", lat: 53.3498, lng: -6.2603, type: "city", wiki: "Dublin", difficulty: 1 },
        { name: "Lisbon", name_he: "ליסבון", emoji: "🚃", lat: 38.7223, lng: -9.1393, type: "city", wiki: "Lisbon", difficulty: 1 },
        { name: "Warsaw", name_he: "ורשה", emoji: "🧜‍♀️", lat: 52.2297, lng: 21.0122, type: "city", wiki: "Warsaw", difficulty: 2 },
        { name: "Budapest", name_he: "בודפשט", emoji: "♨️", lat: 47.4979, lng: 19.0402, type: "city", wiki: "Budapest", difficulty: 1 },
        { name: "Oslo", name_he: "אוסלו", emoji: "⛷️", lat: 59.9139, lng: 10.7522, type: "city", wiki: "Oslo", difficulty: 2 },
        { name: "Helsinki", name_he: "הלסינקי", emoji: "🧊", lat: 60.1699, lng: 24.9384, type: "city", wiki: "Helsinki", difficulty: 2 },
        { name: "Copenhagen", name_he: "קופנהגן", emoji: "🧜‍♀️", lat: 55.6761, lng: 12.5683, type: "city", wiki: "Copenhagen", difficulty: 1 },
        { name: "Havana", name_he: "הוואנה", emoji: "🚗", lat: 23.1136, lng: -82.3666, type: "city", wiki: "Havana", difficulty: 2 },
        { name: "Lima", name_he: "לימה", emoji: "🦙", lat: -12.0464, lng: -77.0428, type: "city", wiki: "Lima", difficulty: 2 },
        { name: "Santiago", name_he: "סנטיאגו", emoji: "🏔️", lat: -33.4489, lng: -70.6693, type: "city", wiki: "Santiago", difficulty: 2 },
        { name: "Bogota", name_he: "בוגוטה", emoji: "🌿", lat: 4.7110, lng: -74.0721, type: "city", wiki: "Bogot%C3%A1", difficulty: 2 },
        { name: "Hanoi", name_he: "האנוי", emoji: "🏮", lat: 21.0278, lng: 105.8342, type: "city", wiki: "Hanoi", difficulty: 2 },
        { name: "Kuala Lumpur", name_he: "קואלה לומפור", emoji: "🏙️", lat: 3.1390, lng: 101.6869, type: "city", wiki: "Kuala_Lumpur", difficulty: 2 },
        { name: "Jakarta", name_he: "ג׳קרטה", emoji: "🏙️", lat: -6.2088, lng: 106.8456, type: "city", wiki: "Jakarta", difficulty: 2 },
        { name: "Manila", name_he: "מנילה", emoji: "🏙️", lat: 14.5995, lng: 120.9842, type: "city", wiki: "Manila", difficulty: 2 },
        { name: "Reykjavik", name_he: "רייקיאוויק", emoji: "🌋", lat: 64.1466, lng: -21.9426, type: "city", wiki: "Reykjav%C3%ADk", difficulty: 2 },
        { name: "Casablanca", name_he: "קזבלנקה", emoji: "🕌", lat: 33.5731, lng: -7.5898, type: "city", wiki: "Casablanca", difficulty: 2 },

        // === NATURE (30) ===
        { name: "Grand Canyon", name_he: "הגרנד קניון", emoji: "🏜️", lat: 36.1069, lng: -112.1129, type: "nature", wiki: "Grand_Canyon", difficulty: 1 },
        { name: "Mount Everest", name_he: "הר אוורסט", emoji: "🏔️", lat: 27.9881, lng: 86.9250, type: "nature", wiki: "Mount_Everest", difficulty: 1 },
        { name: "Amazon River", name_he: "נהר האמזונס", emoji: "🌿", lat: -3.4653, lng: -58.3800, type: "nature", wiki: "Amazon_River", difficulty: 1 },
        { name: "Niagara Falls", name_he: "מפלי ניאגרה", emoji: "💧", lat: 43.0962, lng: -79.0377, type: "nature", wiki: "Niagara_Falls", difficulty: 1 },
        { name: "Victoria Falls", name_he: "מפלי ויקטוריה", emoji: "💧", lat: -17.9243, lng: 25.8572, type: "nature", wiki: "Victoria_Falls", difficulty: 1 },
        { name: "Great Barrier Reef", name_he: "שונית המחסום הגדולה", emoji: "🐠", lat: -18.2871, lng: 147.6992, type: "nature", wiki: "Great_Barrier_Reef", difficulty: 1 },
        { name: "Mount Kilimanjaro", name_he: "הר קילימנג׳רו", emoji: "🏔️", lat: -3.0674, lng: 37.3556, type: "nature", wiki: "Mount_Kilimanjaro", difficulty: 1 },
        { name: "Northern Lights (Iceland)", name_he: "הזוהר הצפוני (איסלנד)", emoji: "🌌", lat: 64.9631, lng: -19.0208, type: "nature", wiki: "Aurora_borealis", difficulty: 1 },
        { name: "Sahara Desert", name_he: "מדבר סהרה", emoji: "🏜️", lat: 23.4162, lng: 25.6628, type: "nature", wiki: "Sahara", difficulty: 1 },
        { name: "Dead Sea", name_he: "ים המלח", emoji: "🧂", lat: 31.5000, lng: 35.5000, type: "nature", wiki: "Dead_Sea", difficulty: 1 },
        { name: "Galapagos Islands", name_he: "איי גלפגוס", emoji: "🐢", lat: -0.9538, lng: -90.9656, type: "nature", wiki: "Gal%C3%A1pagos_Islands", difficulty: 1 },
        { name: "Yellowstone", name_he: "ילוסטון", emoji: "🌋", lat: 44.4280, lng: -110.5885, type: "nature", wiki: "Yellowstone_National_Park", difficulty: 1 },
        { name: "Iguazu Falls", name_he: "מפלי איגואסו", emoji: "💧", lat: -25.6953, lng: -54.4367, type: "nature", wiki: "Iguazu_Falls", difficulty: 1 },
        { name: "Uluru", name_he: "אולורו", emoji: "🪨", lat: -25.3444, lng: 131.0369, type: "nature", wiki: "Uluru", difficulty: 1 },
        { name: "Matterhorn", name_he: "מטרהורן", emoji: "🏔️", lat: 45.9763, lng: 7.6586, type: "nature", wiki: "Matterhorn", difficulty: 2 },
        { name: "Angel Falls", name_he: "מפלי אנג׳ל", emoji: "💧", lat: 5.9701, lng: -62.5362, type: "nature", wiki: "Angel_Falls", difficulty: 2 },
        { name: "Mount Fuji", name_he: "הר פוג׳י", emoji: "🗻", lat: 35.3606, lng: 138.7274, type: "nature", wiki: "Mount_Fuji", difficulty: 1 },
        { name: "Ha Long Bay", name_he: "מפרץ הא לונג", emoji: "🏝️", lat: 20.9101, lng: 107.1839, type: "nature", wiki: "H%E1%BA%A1_Long_Bay", difficulty: 2 },
        { name: "Cliffs of Moher", name_he: "צוקי מוהר", emoji: "🌊", lat: 52.9715, lng: -9.4309, type: "nature", wiki: "Cliffs_of_Moher", difficulty: 2 },
        { name: "Giant's Causeway", name_he: "סוללת הענק", emoji: "🪨", lat: 55.2408, lng: -6.5116, type: "nature", wiki: "Giant%27s_Causeway", difficulty: 2 },
        { name: "Plitvice Lakes", name_he: "אגמי פליטוויצה", emoji: "💧", lat: 44.8654, lng: 15.5820, type: "nature", wiki: "Plitvice_Lakes_National_Park", difficulty: 2 },
        { name: "Blue Lagoon Iceland", name_he: "הלגונה הכחולה באיסלנד", emoji: "♨️", lat: 63.8804, lng: -22.4495, type: "nature", wiki: "Blue_Lagoon_(geothermal_spa)", difficulty: 2 },
        { name: "Zhangjiajie", name_he: "ז׳אנגג׳יאג׳יה", emoji: "🏔️", lat: 29.3249, lng: 110.4343, type: "nature", wiki: "Zhangjiajie_National_Forest_Park", difficulty: 2 },
        { name: "Cappadocia", name_he: "קפדוקיה", emoji: "🎈", lat: 38.6587, lng: 34.8537, type: "nature", wiki: "Cappadocia", difficulty: 2 },
        { name: "Salar de Uyuni", name_he: "סאלאר דה אויוני", emoji: "🪞", lat: -20.1338, lng: -67.4891, type: "nature", wiki: "Salar_de_Uyuni", difficulty: 2 },
        { name: "Serengeti", name_he: "סרנגטי", emoji: "🦁", lat: -2.3333, lng: 34.8333, type: "nature", wiki: "Serengeti", difficulty: 1 },
        { name: "Fjords of Norway", name_he: "הפיורדים של נורווגיה", emoji: "🏔️", lat: 61.7000, lng: 6.7500, type: "nature", wiki: "Geirangerfjord", difficulty: 2 },
        { name: "Great Blue Hole", name_he: "החור הכחול הגדול", emoji: "🌊", lat: 17.3155, lng: -87.5340, type: "nature", wiki: "Great_Blue_Hole", difficulty: 2 },
        { name: "Table Mountain", name_he: "הר השולחן", emoji: "⛰️", lat: -33.9625, lng: 18.4039, type: "nature", wiki: "Table_Mountain", difficulty: 2 },
        { name: "Aurora Borealis (Norway)", name_he: "הזוהר הצפוני (נורווגיה)", emoji: "🌌", lat: 69.6496, lng: 18.9560, type: "nature", wiki: "Aurora_(astronomy)", difficulty: 1 },

        // === HISTORICAL EVENTS (existing + new) ===
        { name: "Invention of Writing", name_he: "המצאת הכתב", emoji: "📜", year: -3200, type: "history", desc: "Cuneiform in Mesopotamia", desc_he: "כתב יתדות במסופוטמיה", difficulty: 2 },
        { name: "Founding of Rome", name_he: "ייסוד רומא", emoji: "🐺", year: -753, type: "history", desc: "Traditional founding by Romulus", desc_he: "הייסוד המסורתי בידי רומולוס", difficulty: 2 },
        { name: "Fall of Rome", name_he: "נפילת רומא", emoji: "⚔️", year: 476, type: "history", desc: "Western Roman Empire collapsed", desc_he: "האימפריה הרומית המערבית קרסה", difficulty: 2 },
        { name: "Magna Carta Signed", name_he: "חתימת המגנא כרטא", emoji: "📜", year: 1215, type: "history", desc: "Foundation of constitutional law", desc_he: "יסוד המשפט החוקתי", difficulty: 2 },
        { name: "Renaissance Begins", name_he: "תחילת הרנסנס", emoji: "🎨", year: 1400, type: "history", desc: "Cultural rebirth in Italy", desc_he: "תחייה תרבותית באיטליה", difficulty: 2 },
        { name: "Gutenberg Printing Press", name_he: "דפוס גוטנברג", emoji: "📰", year: 1440, type: "history", desc: "Revolutionized information spread", desc_he: "חולל מהפכה בהפצת מידע", difficulty: 2 },
        { name: "Columbus Reaches America", name_he: "קולומבוס מגיע לאמריקה", emoji: "⛵", year: 1492, type: "history", desc: "European discovery of the New World", desc_he: "גילוי אירופי של העולם החדש", difficulty: 1 },
        { name: "Industrial Revolution", name_he: "המהפכה התעשייתית", emoji: "🏭", year: 1760, type: "history", desc: "Transition to machine manufacturing", desc_he: "מעבר לייצור מכונות", difficulty: 1 },
        { name: "French Revolution", name_he: "המהפכה הצרפתית", emoji: "🔥", year: 1789, type: "history", desc: "Storming of the Bastille", desc_he: "פריצה לבסטיליה", difficulty: 1 },
        { name: "Suez Canal Opens", name_he: "פתיחת תעלת סואץ", emoji: "⛴️", year: 1869, type: "history", desc: "Connecting Mediterranean and Red Sea", desc_he: "חיבור הים התיכון לים סוף", difficulty: 2 },
        { name: "First Olympic Games (Modern)", name_he: "המשחקים האולימפיים הראשונים", emoji: "🏅", year: 1896, type: "history", desc: "Revived in Athens", desc_he: "חודשו באתונה", difficulty: 1 },
        { name: "Titanic Sinks", name_he: "טביעת הטיטאניק", emoji: "🚢", year: 1912, type: "history", desc: "Unsinkable ship hits an iceberg", desc_he: "האונייה הבלתי ניתנת לטביעה טבעה", difficulty: 1 },
        { name: "World War I Begins", name_he: "פרוץ מלחמת העולם הראשונה", emoji: "💣", year: 1914, type: "history", desc: "The Great War erupts", desc_he: "המלחמה הגדולה פורצת", difficulty: 1 },
        { name: "Panama Canal Opens", name_he: "פתיחת תעלת פנמה", emoji: "🚢", year: 1914, type: "history", desc: "Connecting Atlantic and Pacific", desc_he: "חיבור האוקיינוס האטלנטי לשקט", difficulty: 2 },
        { name: "Women's Suffrage in US", name_he: "זכות בחירה לנשים בארה״ב", emoji: "✊", year: 1920, type: "history", desc: "19th Amendment grants voting rights", desc_he: "התיקון ה-19 מעניק זכות הצבעה", difficulty: 1 },
        { name: "Discovery of Penicillin", name_he: "גילוי הפניצילין", emoji: "💊", year: 1928, type: "history", desc: "Alexander Fleming's breakthrough", desc_he: "פריצת הדרך של אלכסנדר פלמינג", difficulty: 1 },
        { name: "World War II Ends", name_he: "סיום מלחמת העולם השנייה", emoji: "🕊️", year: 1945, type: "history", desc: "Allied victory, end of global conflict", desc_he: "ניצחון בעלות הברית", difficulty: 1 },
        { name: "Mount Everest First Summit", name_he: "כיבוש האוורסט לראשונה", emoji: "⛰️", year: 1953, type: "history", desc: "Hillary and Tenzing reach the top", desc_he: "הילארי וטנזינג מגיעים לפסגה", difficulty: 1 },
        { name: "DNA Structure Discovered", name_he: "גילוי מבנה ה-DNA", emoji: "🧬", year: 1953, type: "history", desc: "Watson and Crick's double helix", desc_he: "הסליל הכפול של ווטסון וקריק", difficulty: 1 },
        { name: "First Moon Landing", name_he: "הנחיתה הראשונה על הירח", emoji: "🌙", year: 1969, type: "history", desc: "Neil Armstrong walks on the Moon", desc_he: "ניל ארמסטרונג הולך על הירח", difficulty: 1 },
        { name: "Fall of the Berlin Wall", name_he: "נפילת חומת ברלין", emoji: "🧱", year: 1989, type: "history", desc: "Symbolic end of the Cold War", desc_he: "סוף סמלי למלחמה הקרה", difficulty: 1 },
        { name: "Nelson Mandela Freed", name_he: "שחרור נלסון מנדלה", emoji: "✊", year: 1990, type: "history", desc: "Released after 27 years in prison", desc_he: "שוחרר אחרי 27 שנות מאסר", difficulty: 1 },
        { name: "Internet Goes Public", name_he: "האינטרנט נפתח לציבור", emoji: "🌐", year: 1991, type: "history", desc: "World Wide Web becomes accessible", desc_he: "הרשת העולמית נגישה לכולם", difficulty: 1 },
        { name: "First iPhone Released", name_he: "השקת האייפון הראשון", emoji: "📱", year: 2007, type: "history", desc: "Apple revolutionized smartphones", desc_he: "אפל חוללה מהפכה בסמארטפונים", difficulty: 1 },
        { name: "COVID-19 Pandemic", name_he: "מגפת הקורונה", emoji: "😷", year: 2020, type: "history", desc: "Global pandemic changes the world", desc_he: "מגפה עולמית משנה את העולם", difficulty: 1 },

        // --- NEW HISTORY EVENTS (40) ---
        { name: "Black Death Reaches Europe", name_he: "המוות השחור מגיע לאירופה", emoji: "☠️", year: 1347, type: "history", desc: "Plague kills millions across Europe", desc_he: "מגפה הורגת מיליונים באירופה", difficulty: 2 },
        { name: "Wright Brothers First Flight", name_he: "הטיסה הראשונה של האחים רייט", emoji: "✈️", year: 1903, type: "history", desc: "First powered airplane flight", desc_he: "טיסת המטוס הממונע הראשונה", difficulty: 1 },
        { name: "Sputnik Launched", name_he: "שיגור ספוטניק", emoji: "🛰️", year: 1957, type: "history", desc: "First artificial satellite in orbit", desc_he: "הלוויין המלאכותי הראשון במסלול", difficulty: 1 },
        { name: "Berlin Wall Built", name_he: "בניית חומת ברלין", emoji: "🧱", year: 1961, type: "history", desc: "Cold War divides Berlin", desc_he: "המלחמה הקרה מחלקת את ברלין", difficulty: 1 },
        { name: "Cuban Missile Crisis", name_he: "משבר הטילים בקובה", emoji: "☢️", year: 1962, type: "history", desc: "Nuclear standoff US vs. USSR", desc_he: "עימות גרעיני בין ארה״ב לברה״מ", difficulty: 1 },
        { name: "Chernobyl Disaster", name_he: "אסון צ׳רנוביל", emoji: "☢️", year: 1986, type: "history", desc: "Nuclear reactor meltdown in USSR", desc_he: "התמוטטות כור גרעיני בברה״מ", difficulty: 1 },
        { name: "September 11 Attacks", name_he: "פיגועי 11 בספטמבר", emoji: "🏢", year: 2001, type: "history", desc: "Terrorist attacks in the US", desc_he: "פיגועי טרור בארצות הברית", difficulty: 1 },
        { name: "Arab Spring Begins", name_he: "תחילת האביב הערבי", emoji: "✊", year: 2010, type: "history", desc: "Protests sweep the Middle East", desc_he: "מחאות גורפות במזרח התיכון", difficulty: 2 },
        { name: "Rosetta Stone Discovered", name_he: "גילוי אבן רוזטה", emoji: "🪨", year: 1799, type: "history", desc: "Key to deciphering hieroglyphs", desc_he: "מפתח לפענוח הירוגליפים", difficulty: 2 },
        { name: "Boston Tea Party", name_he: "מסיבת התה של בוסטון", emoji: "🍵", year: 1773, type: "history", desc: "American colonists protest taxes", desc_he: "מתיישבים אמריקנים מוחים נגד מסים", difficulty: 1 },
        { name: "Battle of Waterloo", name_he: "קרב ווטרלו", emoji: "⚔️", year: 1815, type: "history", desc: "Napoleon's final defeat", desc_he: "תבוסתו האחרונה של נפוליאון", difficulty: 2 },
        { name: "Treaty of Versailles", name_he: "חוזה ורסאי", emoji: "📜", year: 1919, type: "history", desc: "Ended World War I officially", desc_he: "סיים רשמית את מלחה״ע הראשונה", difficulty: 1 },
        { name: "Stock Market Crash 1929", name_he: "קריסת שוק המניות 1929", emoji: "📉", year: 1929, type: "history", desc: "Wall Street crash starts Depression", desc_he: "קריסת וול סטריט פותחת את השפל", difficulty: 1 },
        { name: "Pearl Harbor Attack", name_he: "התקפת פרל הארבור", emoji: "💥", year: 1941, type: "history", desc: "Japan bombs US naval base", desc_he: "יפן מפציצה בסיס ימי אמריקני", difficulty: 1 },
        { name: "D-Day Normandy Invasion", name_he: "פלישת יום D לנורמנדי", emoji: "⚔️", year: 1944, type: "history", desc: "Allied invasion of Nazi Europe", desc_he: "פלישת בעלות הברית לאירופה", difficulty: 1 },
        { name: "Korean War Begins", name_he: "פרוץ מלחמת קוריאה", emoji: "💣", year: 1950, type: "history", desc: "North Korea invades the South", desc_he: "צפון קוריאה פולשת לדרום", difficulty: 2 },
        { name: "Vietnam War Ends", name_he: "סיום מלחמת וייטנאם", emoji: "🕊️", year: 1975, type: "history", desc: "Fall of Saigon ends the war", desc_he: "נפילת סייגון מסיימת את המלחמה", difficulty: 1 },
        { name: "Assassination of JFK", name_he: "רצח ג׳ון פ. קנדי", emoji: "🎯", year: 1963, type: "history", desc: "President Kennedy shot in Dallas", desc_he: "הנשיא קנדי נורה בדאלאס", difficulty: 1 },
        { name: "Cloning of Dolly the Sheep", name_he: "שיבוט הכבשה דולי", emoji: "🐑", year: 1996, type: "history", desc: "First cloned mammal", desc_he: "היונק המשובט הראשון", difficulty: 2 },
        { name: "Human Genome Project Done", name_he: "השלמת פרויקט הגנום האנושי", emoji: "🧬", year: 2003, type: "history", desc: "Complete map of human DNA", desc_he: "מיפוי מלא של ה-DNA האנושי", difficulty: 2 },
        { name: "Bitcoin Created", name_he: "יצירת הביטקוין", emoji: "₿", year: 2009, type: "history", desc: "First decentralized cryptocurrency", desc_he: "המטבע הקריפטוגרפי הראשון", difficulty: 1 },
        { name: "Mars Rover Curiosity Lands", name_he: "נחיתת קיוריוסיטי על מאדים", emoji: "🤖", year: 2012, type: "history", desc: "NASA rover lands on Mars", desc_he: "רובר של נאס״א נוחת על מאדים", difficulty: 2 },
        { name: "Discovery of X-Rays", name_he: "גילוי קרני הרנטגן", emoji: "💀", year: 1895, type: "history", desc: "Roentgen discovers X-radiation", desc_he: "רנטגן מגלה קרינת איקס", difficulty: 2 },
        { name: "Invention of the Telephone", name_he: "המצאת הטלפון", emoji: "📞", year: 1876, type: "history", desc: "Bell patents the telephone", desc_he: "בל רושם פטנט על הטלפון", difficulty: 1 },
        { name: "First Radio Broadcast", name_he: "שידור הרדיו הראשון", emoji: "📻", year: 1920, type: "history", desc: "KDKA begins regular broadcasts", desc_he: "תחילת שידורי רדיו סדירים", difficulty: 2 },
        { name: "First TV Broadcast", name_he: "שידור הטלוויזיה הראשון", emoji: "📺", year: 1928, type: "history", desc: "Baird demonstrates television", desc_he: "בארד מדגים את הטלוויזיה", difficulty: 2 },
        { name: "Splitting the Atom", name_he: "פיצול האטום", emoji: "⚛️", year: 1932, type: "history", desc: "First nuclear fission achieved", desc_he: "ביצוע ביקוע גרעיני ראשון", difficulty: 2 },
        { name: "Polio Vaccine", name_he: "חיסון הפוליו", emoji: "💉", year: 1955, type: "history", desc: "Salk's vaccine saves millions", desc_he: "החיסון של סאלק מציל מיליונים", difficulty: 1 },
        { name: "Berlin Airlift", name_he: "גשר האוויר לברלין", emoji: "✈️", year: 1948, type: "history", desc: "Allies supply blockaded Berlin", desc_he: "בעלות הברית מספקות לברלין", difficulty: 2 },
        { name: "Hungarian Revolution", name_he: "המהפכה ההונגרית", emoji: "✊", year: 1956, type: "history", desc: "Uprising against Soviet rule", desc_he: "מרד נגד השלטון הסובייטי", difficulty: 3 },
        { name: "Six-Day War", name_he: "מלחמת ששת הימים", emoji: "⚔️", year: 1967, type: "history", desc: "Israel defeats Arab coalition", desc_he: "ישראל מנצחת קואליציה ערבית", difficulty: 2 },
        { name: "Camp David Accords", name_he: "הסכמי קמפ דיוויד", emoji: "🤝", year: 1978, type: "history", desc: "Egypt-Israel peace agreement", desc_he: "הסכם שלום מצרים-ישראל", difficulty: 2 },
        { name: "Tiananmen Square Protests", name_he: "מחאות כיכר טיאננמן", emoji: "✊", year: 1989, type: "history", desc: "Pro-democracy protests in Beijing", desc_he: "מחאות פרו-דמוקרטיות בבייג׳ינג", difficulty: 1 },
        { name: "USSR Dissolves", name_he: "התפרקות ברית המועצות", emoji: "🏳️", year: 1991, type: "history", desc: "Soviet Union breaks apart", desc_he: "ברית המועצות מתפרקת", difficulty: 1 },
        { name: "Euro Currency Introduced", name_he: "השקת מטבע האירו", emoji: "💶", year: 2002, type: "history", desc: "Euro coins and notes launched", desc_he: "מטבעות ושטרות אירו מושקים", difficulty: 2 },
        { name: "Fukushima Disaster", name_he: "אסון פוקושימה", emoji: "☢️", year: 2011, type: "history", desc: "Nuclear meltdown after tsunami", desc_he: "התמוטטות גרעינית אחרי צונאמי", difficulty: 1 },
        { name: "Brexit Referendum", name_he: "משאל העם על הברקזיט", emoji: "🗳️", year: 2016, type: "history", desc: "UK votes to leave the EU", desc_he: "בריטניה מצביעה לעזוב את האיחוד", difficulty: 1 },
        { name: "American Civil War Begins", name_he: "פרוץ מלחמת האזרחים האמריקנית", emoji: "⚔️", year: 1861, type: "history", desc: "North vs. South over slavery", desc_he: "צפון מול דרום בנושא העבדות", difficulty: 1 },
        { name: "Abolition of Slavery in US", name_he: "ביטול העבדות בארה״ב", emoji: "⛓️", year: 1865, type: "history", desc: "13th Amendment ends slavery", desc_he: "התיקון ה-13 מבטל את העבדות", difficulty: 1 },
        { name: "Russian Revolution", name_he: "המהפכה הרוסית", emoji: "🔴", year: 1917, type: "history", desc: "Bolsheviks overthrow the Tsar", desc_he: "הבולשביקים מפילים את הצאר", difficulty: 1 },
        { name: "Hiroshima Atomic Bomb", name_he: "הפצצת הירושימה", emoji: "💥", year: 1945, type: "history", desc: "First nuclear weapon used in war", desc_he: "נשק גרעיני ראשון בשימוש מלחמתי", difficulty: 1 },
        { name: "Indian Independence", name_he: "עצמאות הודו", emoji: "🇮🇳", year: 1947, type: "history", desc: "India freed from British rule", desc_he: "הודו משתחררת מהשלטון הבריטי", difficulty: 1 },

];

module.exports = { ALL_CARDS };
