const ALL_CARDS = [

        // === FLAGS (no country name shown, no "from X" hints) ===
        { name: "United States", emoji: "🇺🇸", year: 1776, type: "flag" },
        { name: "France", emoji: "🇫🇷", year: 1794, type: "flag" },
        { name: "Brazil", emoji: "🇧🇷", year: 1822, type: "flag" },
        { name: "Italy", emoji: "🇮🇹", year: 1861, type: "flag" },
        { name: "Germany", emoji: "🇩🇪", year: 1871, type: "flag" },
        { name: "Australia", emoji: "🇦🇺", year: 1901, type: "flag" },
        { name: "Israel", emoji: "🇮🇱", year: 1948, type: "flag" },
        { name: "India", emoji: "🇮🇳", year: 1947, type: "flag" },
        { name: "South Sudan", emoji: "🇸🇸", year: 2011, type: "flag" },
        { name: "Pakistan", emoji: "🇵🇰", year: 1947, type: "flag" },
        { name: "South Africa", emoji: "🇿🇦", year: 1994, type: "flag" },
        { name: "Japan", emoji: "🇯🇵", year: 1870, type: "flag" },
        { name: "Mexico", emoji: "🇲🇽", year: 1821, type: "flag" },
        { name: "Greece", emoji: "🇬🇷", year: 1829, type: "flag" },
        { name: "Canada", emoji: "🇨🇦", year: 1965, type: "flag" },
        { name: "China", emoji: "🇨🇳", year: 1949, type: "flag" },
        { name: "Russia", emoji: "🇷🇺", year: 1991, type: "flag" },
        { name: "Turkey", emoji: "🇹🇷", year: 1923, type: "flag" },
        { name: "Argentina", emoji: "🇦🇷", year: 1816, type: "flag" },
        { name: "Nigeria", emoji: "🇳🇬", year: 1960, type: "flag" },
        { name: "Indonesia", emoji: "🇮🇩", year: 1945, type: "flag" },
        { name: "South Korea", emoji: "🇰🇷", year: 1948, type: "flag" },
        { name: "Ireland", emoji: "🇮🇪", year: 1922, type: "flag" },
        { name: "Egypt", emoji: "🇪🇬", year: 1984, type: "flag" },
        { name: "Norway", emoji: "🇳🇴", year: 1905, type: "flag" },
        { name: "Poland", emoji: "🇵🇱", year: 1918, type: "flag" },
        { name: "Colombia", emoji: "🇨🇴", year: 1810, type: "flag" },
        { name: "Thailand", emoji: "🇹🇭", year: 1917, type: "flag" },
        { name: "Vietnam", emoji: "🇻🇳", year: 1945, type: "flag" },
        { name: "Kenya", emoji: "🇰🇪", year: 1963, type: "flag" },
        { name: "Ukraine", emoji: "🇺🇦", year: 1991, type: "flag" },
        { name: "Chile", emoji: "🇨🇱", year: 1818, type: "flag" },
        { name: "Saudi Arabia", emoji: "🇸🇦", year: 1932, type: "flag" },
        { name: "Jamaica", emoji: "🇯🇲", year: 1962, type: "flag" },
        { name: "Nepal", emoji: "🇳🇵", year: 1962, type: "flag" },
        { name: "Cuba", emoji: "🇨🇺", year: 1902, type: "flag" },
        { name: "Ethiopia", emoji: "🇪🇹", year: 1897, type: "flag" },
        { name: "UAE", emoji: "🇦🇪", year: 1971, type: "flag" },
        { name: "Switzerland", emoji: "🇨🇭", year: 1848, type: "flag" },
        { name: "Denmark", emoji: "🇩🇰", year: 1219, type: "flag" },
        { name: "United Kingdom", emoji: "🇬🇧", year: 1801, type: "flag" },
        { name: "Spain", emoji: "🇪🇸", year: 1981, type: "flag" },
        { name: "Portugal", emoji: "🇵🇹", year: 1910, type: "flag" },
        { name: "Sweden", emoji: "🇸🇪", year: 1906, type: "flag" },
        { name: "Finland", emoji: "🇫🇮", year: 1917, type: "flag" },
        { name: "Belgium", emoji: "🇧🇪", year: 1830, type: "flag" },
        { name: "Netherlands", emoji: "🇳🇱", year: 1815, type: "flag" },
        { name: "Austria", emoji: "🇦🇹", year: 1230, type: "flag" },
        { name: "Czech Republic", emoji: "🇨🇿", year: 1993, type: "flag" },
        { name: "Romania", emoji: "🇷🇴", year: 1848, type: "flag" },
        { name: "Hungary", emoji: "🇭🇺", year: 1918, type: "flag" },
        { name: "Croatia", emoji: "🇭🇷", year: 1991, type: "flag" },
        { name: "Serbia", emoji: "🇷🇸", year: 2006, type: "flag" },
        { name: "Iceland", emoji: "🇮🇸", year: 1944, type: "flag" },
        { name: "New Zealand", emoji: "🇳🇿", year: 1907, type: "flag" },
        { name: "Philippines", emoji: "🇵🇭", year: 1898, type: "flag" },
        { name: "Malaysia", emoji: "🇲🇾", year: 1963, type: "flag" },
        { name: "Singapore", emoji: "🇸🇬", year: 1965, type: "flag" },
        { name: "Bangladesh", emoji: "🇧🇩", year: 1971, type: "flag" },
        { name: "Peru", emoji: "🇵🇪", year: 1821, type: "flag" },
        { name: "Venezuela", emoji: "🇻🇪", year: 1811, type: "flag" },
        { name: "Ecuador", emoji: "🇪🇨", year: 1830, type: "flag" },
        { name: "Morocco", emoji: "🇲🇦", year: 1956, type: "flag" },
        { name: "Tunisia", emoji: "🇹🇳", year: 1956, type: "flag" },
        { name: "Algeria", emoji: "🇩🇿", year: 1962, type: "flag" },
        { name: "Ghana", emoji: "🇬🇭", year: 1957, type: "flag" },
        { name: "Tanzania", emoji: "🇹🇿", year: 1964, type: "flag" },
        { name: "Libya", emoji: "🇱🇾", year: 2011, type: "flag" },
        { name: "Iraq", emoji: "🇮🇶", year: 1932, type: "flag" },
        { name: "Iran", emoji: "🇮🇷", year: 1980, type: "flag" },
        { name: "Jordan", emoji: "🇯🇴", year: 1946, type: "flag" },
        { name: "Lebanon", emoji: "🇱🇧", year: 1943, type: "flag" },
        { name: "Qatar", emoji: "🇶🇦", year: 1971, type: "flag" },
        { name: "Bahrain", emoji: "🇧🇭", year: 1971, type: "flag" },
        { name: "Kuwait", emoji: "🇰🇼", year: 1961, type: "flag" },
        { name: "Oman", emoji: "🇴🇲", year: 1970, type: "flag" },
        { name: "Panama", emoji: "🇵🇦", year: 1903, type: "flag" },
        { name: "Costa Rica", emoji: "🇨🇷", year: 1821, type: "flag" },
        { name: "Dominican Republic", emoji: "🇩🇴", year: 1844, type: "flag" },
        { name: "Haiti", emoji: "🇭🇹", year: 1804, type: "flag" },
        { name: "Bolivia", emoji: "🇧🇴", year: 1825, type: "flag" },
        { name: "Paraguay", emoji: "🇵🇾", year: 1811, type: "flag" },
        { name: "Uruguay", emoji: "🇺🇾", year: 1825, type: "flag" },
        { name: "Sri Lanka", emoji: "🇱🇰", year: 1948, type: "flag" },
        { name: "Myanmar", emoji: "🇲🇲", year: 2010, type: "flag" },
        { name: "Cambodia", emoji: "🇰🇭", year: 1953, type: "flag" },
        { name: "Laos", emoji: "🇱🇦", year: 1975, type: "flag" },
        { name: "Mongolia", emoji: "🇲🇳", year: 1911, type: "flag" },
        { name: "North Korea", emoji: "🇰🇵", year: 1948, type: "flag" },
        { name: "Afghanistan", emoji: "🇦🇫", year: 1919, type: "flag" },
        { name: "Congo (DRC)", emoji: "🇨🇩", year: 1960, type: "flag" },
        { name: "Mozambique", emoji: "🇲🇿", year: 1975, type: "flag" },
        { name: "Zimbabwe", emoji: "🇿🇼", year: 1980, type: "flag" },
        { name: "Namibia", emoji: "🇳🇦", year: 1990, type: "flag" },
        { name: "Eritrea", emoji: "🇪🇷", year: 1993, type: "flag" },
        { name: "East Timor", emoji: "🇹🇱", year: 2002, type: "flag" },
        { name: "Kosovo", emoji: "🇽🇰", year: 2008, type: "flag" },
        { name: "Montenegro", emoji: "🇲🇪", year: 2006, type: "flag" },
        { name: "Albania", emoji: "🇦🇱", year: 1912, type: "flag" },
        { name: "Andorra", emoji: "🇦🇩", year: 1278, type: "flag" },
        { name: "Angola", emoji: "🇦🇴", year: 1975, type: "flag" },
        { name: "Antigua and Barbuda", emoji: "🇦🇬", year: 1981, type: "flag" },
        { name: "Armenia", emoji: "🇦🇲", year: 1991, type: "flag" },
        { name: "Azerbaijan", emoji: "🇦🇿", year: 1991, type: "flag" },
        { name: "Bahamas", emoji: "🇧🇸", year: 1973, type: "flag" },
        { name: "Barbados", emoji: "🇧🇧", year: 1966, type: "flag" },
        { name: "Belarus", emoji: "🇧🇾", year: 1991, type: "flag" },
        { name: "Belize", emoji: "🇧🇿", year: 1981, type: "flag" },
        { name: "Benin", emoji: "🇧🇯", year: 1960, type: "flag" },
        { name: "Bhutan", emoji: "🇧🇹", year: 1949, type: "flag" },
        { name: "Bosnia and Herzegovina", emoji: "🇧🇦", year: 1992, type: "flag" },
        { name: "Botswana", emoji: "🇧🇼", year: 1966, type: "flag" },
        { name: "Brunei", emoji: "🇧🇳", year: 1984, type: "flag" },
        { name: "Bulgaria", emoji: "🇧🇬", year: 1908, type: "flag" },
        { name: "Burkina Faso", emoji: "🇧🇫", year: 1960, type: "flag" },
        { name: "Burundi", emoji: "🇧🇮", year: 1962, type: "flag" },
        { name: "Cabo Verde", emoji: "🇨🇻", year: 1975, type: "flag" },
        { name: "Cameroon", emoji: "🇨🇲", year: 1960, type: "flag" },
        { name: "Central African Republic", emoji: "🇨🇫", year: 1960, type: "flag" },
        { name: "Chad", emoji: "🇹🇩", year: 1960, type: "flag" },
        { name: "Comoros", emoji: "🇰🇲", year: 1975, type: "flag" },
        { name: "Congo (Republic)", emoji: "🇨🇬", year: 1960, type: "flag" },
        { name: "Cyprus", emoji: "🇨🇾", year: 1960, type: "flag" },
        { name: "Djibouti", emoji: "🇩🇯", year: 1977, type: "flag" },
        { name: "Dominica", emoji: "🇩🇲", year: 1978, type: "flag" },
        { name: "El Salvador", emoji: "🇸🇻", year: 1821, type: "flag" },
        { name: "Equatorial Guinea", emoji: "🇬🇶", year: 1968, type: "flag" },
        { name: "Eswatini", emoji: "🇸🇿", year: 1968, type: "flag" },
        { name: "Fiji", emoji: "🇫🇯", year: 1970, type: "flag" },
        { name: "Gabon", emoji: "🇬🇦", year: 1960, type: "flag" },
        { name: "Gambia", emoji: "🇬🇲", year: 1965, type: "flag" },
        { name: "Georgia", emoji: "🇬🇪", year: 1991, type: "flag" },
        { name: "Grenada", emoji: "🇬🇩", year: 1974, type: "flag" },
        { name: "Guatemala", emoji: "🇬🇹", year: 1821, type: "flag" },
        { name: "Guinea", emoji: "🇬🇳", year: 1958, type: "flag" },
        { name: "Guinea-Bissau", emoji: "🇬🇼", year: 1973, type: "flag" },
        { name: "Guyana", emoji: "🇬🇾", year: 1966, type: "flag" },
        { name: "Honduras", emoji: "🇭🇳", year: 1821, type: "flag" },
        { name: "Ivory Coast (Cote d'Ivoire)", emoji: "🇨🇮", year: 1960, type: "flag" },
        { name: "Kazakhstan", emoji: "🇰🇿", year: 1991, type: "flag" },
        { name: "Kiribati", emoji: "🇰🇮", year: 1979, type: "flag" },
        { name: "Kyrgyzstan", emoji: "🇰🇬", year: 1991, type: "flag" },
        { name: "Latvia", emoji: "🇱🇻", year: 1918, type: "flag" },
        { name: "Lesotho", emoji: "🇱🇸", year: 1966, type: "flag" },
        { name: "Liberia", emoji: "🇱🇷", year: 1847, type: "flag" },
        { name: "Liechtenstein", emoji: "🇱🇮", year: 1719, type: "flag" },
        { name: "Lithuania", emoji: "🇱🇹", year: 1918, type: "flag" },
        { name: "Luxembourg", emoji: "🇱🇺", year: 1839, type: "flag" },
        { name: "Madagascar", emoji: "🇲🇬", year: 1960, type: "flag" },
        { name: "Malawi", emoji: "🇲🇼", year: 1964, type: "flag" },
        { name: "Maldives", emoji: "🇲🇻", year: 1965, type: "flag" },
        { name: "Mali", emoji: "🇲🇱", year: 1960, type: "flag" },
        { name: "Malta", emoji: "🇲🇹", year: 1964, type: "flag" },
        { name: "Marshall Islands", emoji: "🇲🇭", year: 1986, type: "flag" },
        { name: "Mauritania", emoji: "🇲🇷", year: 1960, type: "flag" },
        { name: "Mauritius", emoji: "🇲🇺", year: 1968, type: "flag" },
        { name: "Micronesia", emoji: "🇫🇲", year: 1986, type: "flag" },
        { name: "Moldova", emoji: "🇲🇩", year: 1991, type: "flag" },
        { name: "Monaco", emoji: "🇲🇨", year: 1297, type: "flag" },
        { name: "Nicaragua", emoji: "🇳🇮", year: 1821, type: "flag" },
        { name: "Niger", emoji: "🇳🇪", year: 1960, type: "flag" },
        { name: "North Macedonia", emoji: "🇲🇰", year: 1991, type: "flag" },
        { name: "Palau", emoji: "🇵🇼", year: 1994, type: "flag" },
        { name: "Palestine", emoji: "🇵🇸", year: 1988, type: "flag" },
        { name: "Papua New Guinea", emoji: "🇵🇬", year: 1975, type: "flag" },
        { name: "Rwanda", emoji: "🇷🇼", year: 1962, type: "flag" },
        { name: "Saint Kitts and Nevis", emoji: "🇰🇳", year: 1983, type: "flag" },
        { name: "Saint Lucia", emoji: "🇱🇨", year: 1979, type: "flag" },
        { name: "Saint Vincent and the Grenadines", emoji: "🇻🇨", year: 1979, type: "flag" },
        { name: "Samoa", emoji: "🇼🇸", year: 1962, type: "flag" },
        { name: "San Marino", emoji: "🇸🇲", year: 301, type: "flag" },
        { name: "Sao Tome and Principe (Sao Tome)", emoji: "🇸🇹", year: 1975, type: "flag" },
        { name: "Senegal", emoji: "🇸🇳", year: 1960, type: "flag" },
        { name: "Seychelles", emoji: "🇸🇨", year: 1976, type: "flag" },
        { name: "Sierra Leone", emoji: "🇸🇱", year: 1961, type: "flag" },
        { name: "Slovakia", emoji: "🇸🇰", year: 1993, type: "flag" },
        { name: "Slovenia", emoji: "🇸🇮", year: 1991, type: "flag" },
        { name: "Solomon Islands", emoji: "🇸🇧", year: 1978, type: "flag" },
        { name: "Somalia", emoji: "🇸🇴", year: 1960, type: "flag" },
        { name: "Sudan", emoji: "🇸🇩", year: 1956, type: "flag" },
        { name: "Suriname", emoji: "🇸🇷", year: 1975, type: "flag" },
        { name: "Syria", emoji: "🇸🇾", year: 1946, type: "flag" },
        { name: "Taiwan", emoji: "🇹🇼", year: 1949, type: "flag" },
        { name: "Tajikistan", emoji: "🇹🇯", year: 1991, type: "flag" },
        { name: "Togo", emoji: "🇹🇬", year: 1960, type: "flag" },
        { name: "Tonga", emoji: "🇹🇴", year: 1970, type: "flag" },
        { name: "Trinidad and Tobago", emoji: "🇹🇹", year: 1962, type: "flag" },
        { name: "Turkmenistan", emoji: "🇹🇲", year: 1991, type: "flag" },
        { name: "Tuvalu", emoji: "🇹🇻", year: 1978, type: "flag" },
        { name: "Uganda", emoji: "🇺🇬", year: 1962, type: "flag" },
        { name: "Uzbekistan", emoji: "🇺🇿", year: 1991, type: "flag" },
        { name: "Vanuatu", emoji: "🇻🇺", year: 1980, type: "flag" },
        { name: "Vatican City", emoji: "🇻🇦", year: 1929, type: "flag" },
        { name: "Yemen", emoji: "🇾🇪", year: 1990, type: "flag" },
        { name: "Zambia", emoji: "🇿🇲", year: 1964, type: "flag" },

        // === LANDMARKS (existing + new) ===
        { name: "Great Pyramid of Giza", emoji: "🔺", year: -2560, type: "landmark", desc: "Ancient tomb in Egypt", difficulty: 1 },
        { name: "Stonehenge", emoji: "🪨", year: -3000, type: "landmark", desc: "Prehistoric stone circle in England", difficulty: 1 },
        { name: "Parthenon", emoji: "🏛️", year: -432, type: "landmark", desc: "Temple in Athens", difficulty: 2 },
        { name: "Colosseum", emoji: "🏟️", year: 80, type: "landmark", desc: "Amphitheatre in Rome", difficulty: 1 },
        { name: "Hagia Sophia", emoji: "🕌", year: 537, type: "landmark", desc: "Cathedral turned mosque in Istanbul", difficulty: 2 },
        { name: "Angkor Wat", emoji: "🛕", year: 1150, type: "landmark", desc: "Largest religious monument", difficulty: 2 },
        { name: "Notre-Dame Cathedral", emoji: "⛪", year: 1345, type: "landmark", desc: "Gothic cathedral in Paris", difficulty: 1 },
        { name: "Leaning Tower of Pisa", emoji: "🏗️", year: 1372, type: "landmark", desc: "Famous tilted tower in Italy", difficulty: 1 },
        { name: "Machu Picchu", emoji: "🏔️", year: 1450, type: "landmark", desc: "Inca citadel in Peru", difficulty: 1 },
        { name: "Taj Mahal", emoji: "🕌", year: 1653, type: "landmark", desc: "Marble mausoleum in India", difficulty: 1 },
        { name: "Statue of Liberty", emoji: "🗽", year: 1886, type: "landmark", desc: "Iconic statue in New York", difficulty: 1 },
        { name: "Eiffel Tower", emoji: "🗼", year: 1889, type: "landmark", desc: "Iron tower in Paris", difficulty: 1 },
        { name: "Empire State Building", emoji: "🏙️", year: 1931, type: "landmark", desc: "Skyscraper in New York", difficulty: 1 },
        { name: "Golden Gate Bridge", emoji: "🌉", year: 1937, type: "landmark", desc: "Bridge in San Francisco", difficulty: 1 },
        { name: "Sydney Opera House", emoji: "🎭", year: 1973, type: "landmark", desc: "Performing arts center in Australia", difficulty: 1 },
        { name: "Burj Khalifa", emoji: "🏗️", year: 2010, type: "landmark", desc: "Tallest building in the world", difficulty: 1 },
        { name: "Great Wall of China", emoji: "🧱", year: -700, type: "landmark", desc: "Fortification across China", difficulty: 1 },
        { name: "Petra", emoji: "🏜️", year: -312, type: "landmark", desc: "City carved in rock, Jordan", difficulty: 2 },
        { name: "Chichen Itza", emoji: "🏛️", year: 600, type: "landmark", desc: "Mayan pyramid in Mexico", difficulty: 2 },
        { name: "Christ the Redeemer", emoji: "✝️", year: 1931, type: "landmark", desc: "Statue in Rio de Janeiro", difficulty: 1 },

        // --- NEW LANDMARKS (40) ---
        { name: "Kremlin", emoji: "🏰", year: 1495, type: "landmark", desc: "Fortified complex in Moscow", difficulty: 1 },
        { name: "Big Ben", emoji: "🕰️", year: 1859, type: "landmark", desc: "Clock tower in London", difficulty: 1 },
        { name: "Sagrada Familia", emoji: "⛪", year: 1882, type: "landmark", desc: "Gaudi's basilica in Barcelona", difficulty: 2 },
        { name: "Forbidden City", emoji: "🏯", year: 1420, type: "landmark", desc: "Imperial palace in Beijing", difficulty: 2 },
        { name: "Palace of Versailles", emoji: "👑", year: 1682, type: "landmark", desc: "Royal palace near Paris", difficulty: 1 },
        { name: "Acropolis", emoji: "🏛️", year: -447, type: "landmark", desc: "Citadel above Athens", difficulty: 2 },
        { name: "Tower of London", emoji: "🏰", year: 1066, type: "landmark", desc: "Historic castle in London", difficulty: 1 },
        { name: "Pompeii Ruins", emoji: "🌋", year: -600, type: "landmark", desc: "Roman city buried by Vesuvius", difficulty: 2 },
        { name: "Easter Island Moai", emoji: "🗿", year: 1250, type: "landmark", desc: "Stone statues in Pacific Ocean", difficulty: 2 },
        { name: "Mount Rushmore", emoji: "⛰️", year: 1941, type: "landmark", desc: "Presidential faces carved in rock", difficulty: 1 },
        { name: "Sistine Chapel", emoji: "🎨", year: 1512, type: "landmark", desc: "Michelangelo's ceiling in Vatican", difficulty: 2 },
        { name: "Pantheon", emoji: "🏛️", year: 125, type: "landmark", desc: "Ancient temple in Rome", difficulty: 2 },
        { name: "Brandenburg Gate", emoji: "🚪", year: 1791, type: "landmark", desc: "Neoclassical gate in Berlin", difficulty: 2 },
        { name: "Neuschwanstein Castle", emoji: "🏰", year: 1886, type: "landmark", desc: "Fairy-tale castle in Bavaria", difficulty: 2 },
        { name: "Alhambra", emoji: "🕌", year: 1238, type: "landmark", desc: "Moorish palace in Granada, Spain", difficulty: 2 },
        { name: "Blue Mosque", emoji: "🕌", year: 1616, type: "landmark", desc: "Ottoman mosque in Istanbul", difficulty: 2 },
        { name: "Western Wall", emoji: "🧱", year: -19, type: "landmark", desc: "Holy site in Jerusalem", difficulty: 2 },
        { name: "Great Sphinx of Giza", emoji: "🦁", year: -2500, type: "landmark", desc: "Limestone statue in Egypt", difficulty: 1 },
        { name: "Abu Simbel", emoji: "🏛️", year: -1264, type: "landmark", desc: "Rock temples in southern Egypt", difficulty: 3 },
        { name: "Terracotta Army", emoji: "🪖", year: -210, type: "landmark", desc: "Clay soldiers in Xi'an, China", difficulty: 2 },
        { name: "Potala Palace", emoji: "🏯", year: 1649, type: "landmark", desc: "Dalai Lama's palace in Tibet", difficulty: 3 },
        { name: "Borobudur", emoji: "🛕", year: 800, type: "landmark", desc: "Buddhist temple in Java", difficulty: 3 },
        { name: "Pyramids of Teotihuacan", emoji: "🔺", year: 200, type: "landmark", desc: "Ancient pyramids near Mexico City", difficulty: 3 },
        { name: "Mesa Verde", emoji: "🏚️", year: 1190, type: "landmark", desc: "Cliff dwellings in Colorado", difficulty: 3 },
        { name: "Great Zimbabwe", emoji: "🏰", year: 1100, type: "landmark", desc: "Medieval stone city in Africa", difficulty: 3 },
        { name: "Timbuktu", emoji: "🕌", year: 1100, type: "landmark", desc: "Ancient learning center in Mali", difficulty: 3 },
        { name: "Luxor Temple", emoji: "🏛️", year: -1400, type: "landmark", desc: "Ancient temple complex in Egypt", difficulty: 3 },
        { name: "St. Basil's Cathedral", emoji: "⛪", year: 1561, type: "landmark", desc: "Colorful cathedral in Moscow", difficulty: 2 },
        { name: "Opera Garnier", emoji: "🎭", year: 1875, type: "landmark", desc: "Opera house in Paris", difficulty: 3 },
        { name: "Buckingham Palace", emoji: "👑", year: 1703, type: "landmark", desc: "Royal residence in London", difficulty: 1 },
        { name: "Reichstag Building", emoji: "🏛️", year: 1894, type: "landmark", desc: "Parliament building in Berlin", difficulty: 2 },
        { name: "Tokyo Tower", emoji: "🗼", year: 1958, type: "landmark", desc: "Broadcast tower in Tokyo", difficulty: 1 },
        { name: "CN Tower", emoji: "🗼", year: 1976, type: "landmark", desc: "Communications tower in Toronto", difficulty: 2 },
        { name: "Space Needle", emoji: "🗼", year: 1962, type: "landmark", desc: "Observation tower in Seattle", difficulty: 1 },
        { name: "Panama Canal", emoji: "🚢", year: 1914, type: "landmark", desc: "Waterway connecting two oceans", difficulty: 1 },
        { name: "Suez Canal", emoji: "⛴️", year: 1869, type: "landmark", desc: "Waterway connecting two seas", difficulty: 2 },
        { name: "Petra Treasury", emoji: "🏜️", year: -100, type: "landmark", desc: "Carved facade in Jordan", difficulty: 2 },
        { name: "Moai of Ahu Tongariki", emoji: "🗿", year: 1450, type: "landmark", desc: "Largest moai platform on Easter Is.", difficulty: 3 },
        { name: "Persepolis", emoji: "🏛️", year: -515, type: "landmark", desc: "Ancient Persian capital ruins", difficulty: 3 },
        { name: "Newgrange", emoji: "🪨", year: -3200, type: "landmark", desc: "Prehistoric tomb in Ireland", difficulty: 3 },

        // === HISTORICAL EVENTS (existing + new) ===
        { name: "Invention of Writing", emoji: "📜", year: -3200, type: "history", desc: "Cuneiform in Mesopotamia", difficulty: 2 },
        { name: "Founding of Rome", emoji: "🐺", year: -753, type: "history", desc: "Traditional founding by Romulus", difficulty: 2 },
        { name: "Fall of Rome", emoji: "⚔️", year: 476, type: "history", desc: "Western Roman Empire collapsed", difficulty: 2 },
        { name: "Magna Carta Signed", emoji: "📜", year: 1215, type: "history", desc: "Foundation of constitutional law", difficulty: 2 },
        { name: "Renaissance Begins", emoji: "🎨", year: 1400, type: "history", desc: "Cultural rebirth in Italy", difficulty: 2 },
        { name: "Gutenberg Printing Press", emoji: "📰", year: 1440, type: "history", desc: "Revolutionized information spread", difficulty: 2 },
        { name: "Columbus Reaches America", emoji: "⛵", year: 1492, type: "history", desc: "European discovery of the New World", difficulty: 1 },
        { name: "Industrial Revolution", emoji: "🏭", year: 1760, type: "history", desc: "Transition to machine manufacturing", difficulty: 1 },
        { name: "French Revolution", emoji: "🔥", year: 1789, type: "history", desc: "Storming of the Bastille", difficulty: 1 },
        { name: "Suez Canal Opens", emoji: "⛴️", year: 1869, type: "history", desc: "Connecting Mediterranean and Red Sea", difficulty: 2 },
        { name: "First Olympic Games (Modern)", emoji: "🏅", year: 1896, type: "history", desc: "Revived in Athens", difficulty: 1 },
        { name: "Titanic Sinks", emoji: "🚢", year: 1912, type: "history", desc: "Unsinkable ship hits an iceberg", difficulty: 1 },
        { name: "World War I Begins", emoji: "💣", year: 1914, type: "history", desc: "The Great War erupts", difficulty: 1 },
        { name: "Panama Canal Opens", emoji: "🚢", year: 1914, type: "history", desc: "Connecting Atlantic and Pacific", difficulty: 2 },
        { name: "Women's Suffrage in US", emoji: "✊", year: 1920, type: "history", desc: "19th Amendment grants voting rights", difficulty: 1 },
        { name: "Discovery of Penicillin", emoji: "💊", year: 1928, type: "history", desc: "Alexander Fleming's breakthrough", difficulty: 1 },
        { name: "World War II Ends", emoji: "🕊️", year: 1945, type: "history", desc: "Allied victory, end of global conflict", difficulty: 1 },
        { name: "Mount Everest First Summit", emoji: "⛰️", year: 1953, type: "history", desc: "Hillary and Tenzing reach the top", difficulty: 1 },
        { name: "DNA Structure Discovered", emoji: "🧬", year: 1953, type: "history", desc: "Watson and Crick's double helix", difficulty: 1 },
        { name: "First Moon Landing", emoji: "🌙", year: 1969, type: "history", desc: "Neil Armstrong walks on the Moon", difficulty: 1 },
        { name: "Fall of the Berlin Wall", emoji: "🧱", year: 1989, type: "history", desc: "Symbolic end of the Cold War", difficulty: 1 },
        { name: "Nelson Mandela Freed", emoji: "✊", year: 1990, type: "history", desc: "Released after 27 years in prison", difficulty: 1 },
        { name: "Internet Goes Public", emoji: "🌐", year: 1991, type: "history", desc: "World Wide Web becomes accessible", difficulty: 1 },
        { name: "First iPhone Released", emoji: "📱", year: 2007, type: "history", desc: "Apple revolutionized smartphones", difficulty: 1 },
        { name: "COVID-19 Pandemic", emoji: "😷", year: 2020, type: "history", desc: "Global pandemic changes the world", difficulty: 1 },

        // --- NEW HISTORY EVENTS (40) ---
        { name: "Black Death Reaches Europe", emoji: "☠️", year: 1347, type: "history", desc: "Plague kills millions across Europe", difficulty: 2 },
        { name: "Wright Brothers First Flight", emoji: "✈️", year: 1903, type: "history", desc: "First powered airplane flight", difficulty: 1 },
        { name: "Sputnik Launched", emoji: "🛰️", year: 1957, type: "history", desc: "First artificial satellite in orbit", difficulty: 1 },
        { name: "Berlin Wall Built", emoji: "🧱", year: 1961, type: "history", desc: "Cold War divides Berlin", difficulty: 1 },
        { name: "Cuban Missile Crisis", emoji: "☢️", year: 1962, type: "history", desc: "Nuclear standoff US vs. USSR", difficulty: 1 },
        { name: "Chernobyl Disaster", emoji: "☢️", year: 1986, type: "history", desc: "Nuclear reactor meltdown in USSR", difficulty: 1 },
        { name: "September 11 Attacks", emoji: "🏢", year: 2001, type: "history", desc: "Terrorist attacks in the US", difficulty: 1 },
        { name: "Arab Spring Begins", emoji: "✊", year: 2010, type: "history", desc: "Protests sweep the Middle East", difficulty: 2 },
        { name: "Rosetta Stone Discovered", emoji: "🪨", year: 1799, type: "history", desc: "Key to deciphering hieroglyphs", difficulty: 2 },
        { name: "Boston Tea Party", emoji: "🍵", year: 1773, type: "history", desc: "American colonists protest taxes", difficulty: 1 },
        { name: "Battle of Waterloo", emoji: "⚔️", year: 1815, type: "history", desc: "Napoleon's final defeat", difficulty: 2 },
        { name: "Treaty of Versailles", emoji: "📜", year: 1919, type: "history", desc: "Ended World War I officially", difficulty: 1 },
        { name: "Stock Market Crash 1929", emoji: "📉", year: 1929, type: "history", desc: "Wall Street crash starts Depression", difficulty: 1 },
        { name: "Pearl Harbor Attack", emoji: "💥", year: 1941, type: "history", desc: "Japan bombs US naval base", difficulty: 1 },
        { name: "D-Day Normandy Invasion", emoji: "⚔️", year: 1944, type: "history", desc: "Allied invasion of Nazi Europe", difficulty: 1 },
        { name: "Korean War Begins", emoji: "💣", year: 1950, type: "history", desc: "North Korea invades the South", difficulty: 2 },
        { name: "Vietnam War Ends", emoji: "🕊️", year: 1975, type: "history", desc: "Fall of Saigon ends the war", difficulty: 1 },
        { name: "Assassination of JFK", emoji: "🎯", year: 1963, type: "history", desc: "President Kennedy shot in Dallas", difficulty: 1 },
        { name: "Cloning of Dolly the Sheep", emoji: "🐑", year: 1996, type: "history", desc: "First cloned mammal", difficulty: 2 },
        { name: "Human Genome Project Done", emoji: "🧬", year: 2003, type: "history", desc: "Complete map of human DNA", difficulty: 2 },
        { name: "Bitcoin Created", emoji: "₿", year: 2009, type: "history", desc: "First decentralized cryptocurrency", difficulty: 1 },
        { name: "Mars Rover Curiosity Lands", emoji: "🤖", year: 2012, type: "history", desc: "NASA rover lands on Mars", difficulty: 2 },
        { name: "Discovery of X-Rays", emoji: "💀", year: 1895, type: "history", desc: "Roentgen discovers X-radiation", difficulty: 2 },
        { name: "Invention of the Telephone", emoji: "📞", year: 1876, type: "history", desc: "Bell patents the telephone", difficulty: 1 },
        { name: "First Radio Broadcast", emoji: "📻", year: 1920, type: "history", desc: "KDKA begins regular broadcasts", difficulty: 2 },
        { name: "First TV Broadcast", emoji: "📺", year: 1928, type: "history", desc: "Baird demonstrates television", difficulty: 2 },
        { name: "Splitting the Atom", emoji: "⚛️", year: 1932, type: "history", desc: "First nuclear fission achieved", difficulty: 2 },
        { name: "Polio Vaccine", emoji: "💉", year: 1955, type: "history", desc: "Salk's vaccine saves millions", difficulty: 1 },
        { name: "Berlin Airlift", emoji: "✈️", year: 1948, type: "history", desc: "Allies supply blockaded Berlin", difficulty: 2 },
        { name: "Hungarian Revolution", emoji: "✊", year: 1956, type: "history", desc: "Uprising against Soviet rule", difficulty: 3 },
        { name: "Six-Day War", emoji: "⚔️", year: 1967, type: "history", desc: "Israel defeats Arab coalition", difficulty: 2 },
        { name: "Camp David Accords", emoji: "🤝", year: 1978, type: "history", desc: "Egypt-Israel peace agreement", difficulty: 2 },
        { name: "Tiananmen Square Protests", emoji: "✊", year: 1989, type: "history", desc: "Pro-democracy protests in Beijing", difficulty: 1 },
        { name: "USSR Dissolves", emoji: "🏳️", year: 1991, type: "history", desc: "Soviet Union breaks apart", difficulty: 1 },
        { name: "Euro Currency Introduced", emoji: "💶", year: 2002, type: "history", desc: "Euro coins and notes launched", difficulty: 2 },
        { name: "Fukushima Disaster", emoji: "☢️", year: 2011, type: "history", desc: "Nuclear meltdown after tsunami", difficulty: 1 },
        { name: "Brexit Referendum", emoji: "🗳️", year: 2016, type: "history", desc: "UK votes to leave the EU", difficulty: 1 },
        { name: "American Civil War Begins", emoji: "⚔️", year: 1861, type: "history", desc: "North vs. South over slavery", difficulty: 1 },
        { name: "Abolition of Slavery in US", emoji: "⛓️", year: 1865, type: "history", desc: "13th Amendment ends slavery", difficulty: 1 },
        { name: "Russian Revolution", emoji: "🔴", year: 1917, type: "history", desc: "Bolsheviks overthrow the Tsar", difficulty: 1 },
        { name: "Hiroshima Atomic Bomb", emoji: "💥", year: 1945, type: "history", desc: "First nuclear weapon used in war", difficulty: 1 },
        { name: "Indian Independence", emoji: "🇮🇳", year: 1947, type: "history", desc: "India freed from British rule", difficulty: 1 },

];

module.exports = { ALL_CARDS };
